// Run: node verify_question_data_save.mjs
// Extracts buildCleanData/buildTypeData from AdminApp.jsx and checks what a save keeps.
import { readFileSync } from "node:fs";
const src = readFileSync("src/screens/AdminApp.jsx", "utf8");
const grab = (name) => { const i = src.indexOf(`function ${name}(`); let depth = 0, j = src.indexOf("{", i); for (let k = j; k < src.length; k++) { if (src[k] === "{") depth++; else if (src[k] === "}" && --depth === 0) return src.slice(i, k + 1); } };
const buildCleanData = new Function(`${grab("buildTypeData")}\n${grab("buildCleanData")}\nreturn buildCleanData;`)();
let fail = 0; const check = (label, ok, got) => { console.log(`${ok ? "PASS" : "FAIL"}  ${label}${ok ? "" : "  got " + JSON.stringify(got)}`); if (!ok) fail++; };
const ar = { assertion: "S1", reason: "S2", ar_labels: "statement", closing: "Which one of the following is correct in respect of the above statements?", fixed_option_order: true };
const outAr = buildCleanData("assertion_reason", ar);
check("Statement-I/II row keeps ar_labels", outAr.ar_labels === "statement", outAr);
check("Statement-I/II row keeps its closing line", outAr.closing === ar.closing, outAr);
check("Statement-I/II row keeps fixed_option_order", outAr.fixed_option_order === true, outAr);
const outBpsc = buildCleanData("assertion_reason", { assertion: "A", reason: "R" });
check("BPSC-style A/R row gains no new keys", JSON.stringify(Object.keys(outBpsc)) === JSON.stringify(["assertion", "reason"]), outBpsc);
const outMatch = buildCleanData("match_the_following", { list_1: ["1. x"], list_2: ["y"], closing: "How many of the pairs given above are correctly matched?", fixed_option_order: true });
check("match row still keeps its closing line (earlier fix)", !!outMatch.closing && outMatch.fixed_option_order === true, outMatch);
const outStmt = buildCleanData("statement_based", { statements: ["a", "b"], closing: "Which of the statements given above is/are correct?", fixed_option_order: true });
check("statement row keeps closing + fixed order", !!outStmt.closing && outStmt.fixed_option_order === true, outStmt);
check("Arabic-numbered statement row gains no numbering key", !("numbering" in outStmt), outStmt);
const outRoman = buildCleanData("statement_based", { statements: ["a", "b", "c"], numbering: "roman", fixed_option_order: true });
check("Roman-numbered statement row keeps numbering", outRoman.numbering === "roman" && outRoman.fixed_option_order === true, outRoman);
const outUnticked = buildCleanData("statement_based", { statements: ["a", "b"], numbering: undefined });
check("unticking Roman numbering drops the key", !("numbering" in outUnticked), outUnticked);
const outMcqStray = buildCleanData("mcq", { statements: ["a"], numbering: "roman" });
check("an MCQ never carries a stray numbering key", !("numbering" in outMcqStray), outMcqStray);
const si3 = { assertion: "S1", reason: "S2", reason_2: " S3 ", reason_2_hi: "कथन 3", ar_labels: "statement", closing: "Which one of the following is correct in respect of the above statements?", fixed_option_order: true };
const outSi3 = buildCleanData("assertion_reason", si3);
check("Statement-I/II/III row keeps Statement-III (trimmed) and its Hindi", outSi3.reason_2 === "S3" && outSi3.reason_2_hi === "कथन 3" && outSi3.ar_labels === "statement", outSi3);
const outSi3Blank = buildCleanData("assertion_reason", { ...si3, reason_2: "   ", reason_2_hi: "" });
check("a blank Statement-III is not saved", !("reason_2" in outSi3Blank) && !("reason_2_hi" in outSi3Blank), outSi3Blank);
const outArWithThird = buildCleanData("assertion_reason", { assertion: "A", reason: "R", reason_2: "stray" });
check("Assertion/Reason wording never carries a Statement-III", !("reason_2" in outArWithThird), outArWithThird);
check("two-statement Statement-I/II row gains no reason_2 key", !("reason_2" in outAr), outAr);
console.log(fail ? `\n${fail} FAILED` : "\nALL PASS"); process.exit(fail ? 1 : 0);
