"""71st BPSC Prelims (13 Sep 2025), Set E, 4-option. FINAL key.
Tagged from English (official standard). correct_option auto-filled from official Set-E FINAL key.
"""
import os
from schema import COLUMNS, write_rows

KEY = {1:"C",2:"A",3:"D",4:"A",5:"B",6:"D",7:"A",8:"D",9:"B",10:"D",11:"Deleted",12:"C",13:"D",14:"C",15:"B",
16:"A",17:"C",18:"B",19:"B",20:"C",21:"D",22:"D",23:"C",24:"C",25:"B",26:"A",27:"B",28:"B",29:"C",30:"D",
31:"D",32:"D",33:"B",34:"B",35:"A",36:"A",37:"C",38:"C",39:"B",40:"D",41:"B",42:"A",43:"B",44:"A",45:"B",
46:"C",47:"A",48:"C",49:"B",50:"A",51:"C",52:"C",53:"D",54:"A",55:"B",56:"D",57:"B",58:"A",59:"C",60:"C",
61:"B",62:"A",63:"A",64:"C",65:"D",66:"D",67:"C",68:"D",69:"Deleted",70:"C",71:"B",72:"C",73:"C",74:"D",75:"Deleted",
76:"C",77:"D",78:"B",79:"B",80:"C",81:"B",82:"A",83:"B",84:"D",85:"D",86:"B",87:"B",88:"A",89:"C",90:"A",
91:"C",92:"A",93:"A",94:"B",95:"D",96:"Deleted",97:"B",98:"B",99:"B",100:"D",101:"B",102:"A",103:"B",104:"B",105:"A",
106:"B",107:"C",108:"D",109:"D",110:"D",111:"A",112:"C",113:"B",114:"A",115:"B",116:"D",117:"A",118:"Deleted",119:"B",120:"A",
121:"B",122:"D",123:"C",124:"A",125:"B",126:"C",127:"D",128:"B",129:"C",130:"A",131:"A",132:"A",133:"A",134:"A",135:"B",
136:"D",137:"C",138:"C",139:"D",140:"D",141:"C",142:"A",143:"A",144:"C",145:"A",146:"A",147:"C",148:"B",149:"A",150:"D"}

DEF = dict(year="71st", exam_date="2025-09-13", paper_variant="main", booklet_series="E",
           option_count=4, key_status="final", statement_count="", list_item_count="",
           option_combination_pattern="", is_all_or_none_correct="FALSE",
           all_none_literal_phrasing="FALSE", ambiguous_subject="FALSE", ambiguous_note="",
           ca_recency_months="")

def r(qn, subject, sub, qtype, diff, src, text, **kw):
    row = dict(DEF); row.update(kw)
    row.update(question_number=qn, subject=subject, sub_topic=sub, question_type=qtype,
               difficulty_guess=diff, source_type_guess=src, question_text_en=text,
               correct_option=KEY[qn])
    return row

ST, MT, MCQ, AR, RA = "statement_based", "match_the_following", "simple_mcq", "assertion_reason", "reasoning_aptitude"
ROWS = [
 r(1,"Reasoning & Aptitude","Logical/Verbal",RA,"easy","specialized reference","Odd one out (Microscope/Telescope/Stethoscope/Periscope)"),
 r(2,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Code: SPRING=UNUFRC -> MOBILE"),
 r(3,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Blood relation: Mukesh & Rita (Father-in-law)"),
 r(4,"Reasoning & Aptitude","Logical/Verbal",RA,"easy","specialized reference","Direction: Ram goes North, right, right, left (East)"),
 r(5,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Alphabetical order — which name appears last"),
 r(6,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Ranking: Nitin's rank from the beginning (16th)"),
 r(7,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Symbol-substitution arithmetic (77)"),
 r(8,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Ages of Seema and Laxmi (9, 50)"),
 r(9,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Missing number in 3x3 matrix (35)"),
 r(10,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Code: RAIN=8$%6, MORE=7#8@ -> REMAIN"),
 r(11,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Bronze medals by Bihar in 38th Nat'l Junior Athletics C'ship 2025 (Deleted)",ambiguous_subject="TRUE",ambiguous_note="Bihar sports — could be Current Affairs/Sports"),
 r(12,"Bihar-Specific","Geography",MCQ,"medium","current_affairs","Districts benefiting from Kosi-Mechi Link Project (Araria, Purnea, Kishanganj, Katihar)"),
 r(13,"Current Affairs","National",MCQ,"medium","current_affairs","Indian languages accorded Classical Language status (More than one)"),
 r(14,"Environment & Ecology","Biodiversity",MCQ,"medium","current_affairs","Org that recognized Nagi Bird Sanctuary as IBA (Bird Life International)",ambiguous_subject="TRUE",ambiguous_note="Nagi is in Bihar"),
 r(15,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Where National Panchayati Raj Day 2025 event was organised (Madhubani)",ca_recency_months=5),
 r(16,"Science & Technology","Tech & Innovation",MCQ,"medium","current_affairs","Primary objective of Lunar Trailblazer mission (map water on Moon)",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(17,"Current Affairs","International",MCQ,"easy","current_affairs","Afrikaners indicate which people (white minority in South Africa)",ambiguous_subject="TRUE",ambiguous_note="static GK"),
 r(18,"Current Affairs","National",MCQ,"medium","current_affairs","16th-century stepwell conserved by ASI + World Monuments Fund (Rajon ki Baoli)",ambiguous_subject="TRUE",ambiguous_note="could be History/Art & Culture"),
 r(19,"Current Affairs","International",MCQ,"medium","current_affairs","NYC mayor who proclaimed Apr 14 2025 Ambedkar Day (Eric Adams)",ca_recency_months=5),
 r(20,"Current Affairs","International",MCQ,"medium","current_affairs","Permanent slogan of Eurovision Song Contest (United By Music)"),
 r(21,"Science & Technology","Tech & Innovation",MCQ,"medium","current_affairs","What is true of ISRO's GSLV-F15 mission (More than one)",ca_recency_months=7,ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(22,"Current Affairs","International",MCQ,"medium","current_affairs","What is true of the 18th G20 Summit (More than one)"),
 r(23,"Environment & Ecology","Climate & Pollution",MCQ,"medium","current_affairs","COP29 (Baku 2024) climate finance agreement ($300bn by 2035)",ca_recency_months=10,ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(24,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Han Kang's 'The Vegetarian' won which award (International Booker)"),
 r(25,"Environment & Ecology","Climate & Pollution",MCQ,"medium","current_affairs","Nepal glacier declared 'dead' May 2025 (Yala Glacier)",ca_recency_months=4),
 r(26,"Current Affairs","Schemes & Indices",MCQ,"medium","current_affairs","UNDP HDI 2025 — India life expectancy in 2023 (72 years)"),
 r(27,"Current Affairs","International",MCQ,"medium","current_affairs","AI Action Summit Feb 2025 city (Paris)",ca_recency_months=7),
 r(28,"Current Affairs","Awards & Appointments",MCQ,"easy","current_affairs","96th Academy Awards — Emma Stone Best Actress film (Poor Things)",ca_recency_months=18),
 r(29,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Gujarati film that won 70th National Film Award Best Feature (Kutch Express)"),
 r(30,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Ramon Magsaysay Award 2024 recipient (More than one)"),
 r(31,"Science & Technology","Tech & Innovation",MCQ,"medium","current_affairs","Statements about Akashteer (Army Air Defence) (More than one)",ambiguous_subject="TRUE",ambiguous_note="defence — could be Current Affairs"),
 r(32,"Science & Technology","Tech & Innovation",MCQ,"medium","current_affairs","Make-in-India indigenous defence platforms (More than one)",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(33,"Current Affairs","International",MCQ,"easy","specialized reference","Holocaust Memorial Day observed on (January 27)"),
 r(34,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Banu Mushtaq's book that won 2025 International Booker (Heart Lamp)",ca_recency_months=4),
 r(35,"Geography","Physical",MCQ,"medium","NCERT-level","Indus Waters Treaty eastern rivers — which is NOT one (Jhelum)"),
 r(36,"Economy","Macroeconomic concepts",ST,"hard","specialized reference","Capability Poverty Measure (CPM/UNDP) statements — which correct",statement_count=4,option_combination_pattern="1 and 2",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs/Indices"),
 r(37,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","NOT among top-ten export commodities Apr-Sep 2024-25 (Basmati Rice)"),
 r(38,"Environment & Ecology","Conservation & Policy",MCQ,"hard","current_affairs","India State of Forest Report 2023 — which statement is correct"),
 r(39,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","Country with greater share than India in global services export 2023 (Ireland)"),
 r(40,"Current Affairs","Schemes & Indices",MCQ,"medium","current_affairs","U-WIN portal statements — which NOT correct (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(41,"Current Affairs","Schemes & Indices",MCQ,"hard","current_affairs","Org that jointly developed NUIS Digital Blueprint with MoHUA (NIUA)"),
 r(42,"Economy","Five-year plans & policy",MCQ,"medium","current_affairs","State with highest road length under Bharatmala (31 Oct 2024) (Rajasthan)",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(43,"Economy","Banking & finance",MCQ,"hard","current_affairs","Institution for Interest Subvention claims before Kisan Rin Portal (RBI & NABARD)"),
 r(44,"Economy","Banking & finance",MCQ,"medium","current_affairs","India's forex reserves (increased to ~USD 640 bn end Dec 2024)"),
 r(45,"Current Affairs","Schemes & Indices",MCQ,"medium","current_affairs","NFHS-5 — state with <6% multidimensionally poor 2019-20 (Himachal Pradesh)",ambiguous_subject="TRUE",ambiguous_note="could be Economy"),
 r(46,"Environment & Ecology","Conservation & Policy",MT,"hard","current_affairs","Match schemes with descriptions (PAT, MISHTI, LiFE, NCAP)",list_item_count=4),
 r(47,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","PLFS 2023-24 report — which statement correct (rural female LFPR)"),
 r(48,"Science & Technology","Tech & Innovation",MCQ,"hard","current_affairs","NOT an outcome of STI Policy 2020 (Atal Innovation Mission)",ambiguous_subject="TRUE",ambiguous_note="could be Economy/policy"),
 r(49,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","MSME share in GVA 2020-21 to 2022-23 (27.3% to 30.1%)"),
 r(50,"Economy","Macroeconomic concepts",ST,"hard","specialized reference","Indian cement industry statements — which correct",statement_count=3,option_combination_pattern="Only 1"),
 r(51,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Primary objective of Bihar's Mission Daksh (personalised mentoring)"),
 r(52,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","NOT a YUVA-framework component of Bihar Startup Policy 2022 (Intl market expansion)"),
 r(53,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","Bihar economic performance 2023-24 — which correct (More than one)"),
 r(54,"Bihar-Specific","Economy",ST,"hard","specialized reference","Bihar demographic statements — which correct",statement_count=3,option_combination_pattern="1 and 2"),
 r(55,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","PLFS 2023-24 — nature of women's employment in Bihar (self-employed helpers)"),
 r(56,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Power to recruit Secretarial staff of the House of the People (President + Speaker)"),
 r(57,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Attorney General of India — which is true"),
 r(58,"Polity","Constitutional provisions",ST,"hard","NCERT-level","Which subjects belong to the Concurrent List",statement_count=4,option_combination_pattern="1 and 4"),
 r(59,"Polity","Constitutional provisions",ST,"medium","NCERT-level","Which DPSP do NOT follow Gandhian Principles",statement_count=4,option_combination_pattern="2 and 4"),
 r(60,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Which schedule-pair is NOT correctly matched"),
 r(61,"Polity","Constitutional provisions",ST,"medium","NCERT-level","Central Government statements — which correct",statement_count=2,option_combination_pattern="Only 2"),
 r(62,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Proceedings of the State Legislature — what is true"),
 r(63,"Polity","Constitutional provisions",ST,"hard","specialized reference","Reasonable restrictions on Fundamental Rights statements — which correct",statement_count=4,option_combination_pattern="1 and 2"),
 r(64,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Who determines qualification for Finance Commission member (Parliament by act)"),
 r(65,"Polity","Constitutional provisions",ST,"hard","NCERT-level","Summoning/Prorogation/Dissolution statements — which NOT true",statement_count=4,option_combination_pattern="Only 4"),
 r(66,"Polity","Panchayati Raj & local governance",MCQ,"medium","NCERT-level","Who reviews financial position of Panchayats (Finance Commission by Governor)"),
 r(67,"Economy","Five-year plans & policy",ST,"medium","NCERT-level","Atmanirbhar Bharat Scheme helps in — statements",statement_count=2,option_combination_pattern="Both 1 and 2"),
 r(68,"Polity","Panchayati Raj & local governance",MCQ,"medium","NCERT-level","Main purpose of Panchayati Raj (participate in development admin)"),
 r(69,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","What is true about Censure Motion (Deleted)"),
 r(70,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Subject in jurisdiction of both HC and SC (protection of FRs)"),
 r(71,"History","Modern",MCQ,"medium","specialized reference","Leader who first used 'safety-valve theory' vs Moderates (Lala Lajpat Rai)"),
 r(72,"History","Modern",MCQ,"medium","specialized reference","Viceroy at whose Delhi state entry a bomb was thrown (Lord Hardinge)"),
 r(73,"History","Modern",MCQ,"hard","specialized reference","Professor of Indian Philosophy at Univ of California 1911 (Har Dayal)"),
 r(74,"History","Modern",MCQ,"hard","specialized reference","MAO College Aligarh Principal who encouraged Muslim communalism (Theodore Beck)"),
 r(75,"History","Modern",MCQ,"medium","specialized reference","'The Young India' Nationalist paper started by (Deleted)"),
 r(76,"History","Modern",MCQ,"medium","NCERT-level","Commission that accentuated discontent (no Indian member) (Simon Commission)"),
 r(77,"History","Modern",MCQ,"easy","NCERT-level","Who assumed INA command and gave 'Chalo Delhi' (Subhash Chandra Bose)"),
 r(78,"History","Modern",MCQ,"medium","specialized reference","'We shall either free India or die...' who said it (Mahatma Gandhi)"),
 r(79,"History","Modern",MCQ,"medium","specialized reference","Who raised the cry 'Divide and Quit' (M.A. Jinnah)"),
 r(80,"History","Modern",MCQ,"easy","NCERT-level","Act that provided for partition into India and Pakistan (Indian Independence Act 1947)"),
 r(81,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Congress leader who visited Bihar 1918 for Home Rule League (Annie Besant)"),
 r(82,"Bihar-Specific","History & Culture",MCQ,"medium","NCERT-level","Champaran Agrarian Committee — agreement between (Govt and Gandhiji)"),
 r(83,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Prominent leader of Kisan Sabha movement in Bihar (Sahajanand Saraswati)"),
 r(84,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Who was murdered hoisting flag near Bikram Police Station (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(85,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Who became CM of Bihar in March 1939 (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(86,"History","Ancient",MT,"hard","specialized reference","Match ancient India places with present state (Karnasuvarna, Pragjyotish, Girnar, Pratishthan)",list_item_count=4),
 r(87,"History","Ancient",MCQ,"medium","specialized reference","Which is NOT related to the Rigvedic period (Gargi)"),
 r(88,"History","Ancient",MT,"hard","specialized reference","Match event/place with person (Chola Gangam Lake, Dharma Mahamatra, Prayag, Sudarshan Lake)",list_item_count=4),
 r(89,"History","Medieval",MCQ,"medium","specialized reference","Which ruler ruled for the maximum period (Bahlol Lodi)"),
 r(90,"History","Ancient",ST,"medium","NCERT-level","Chronological order of dynasties (Shunga, Maurya, Kushana, Kanva)",statement_count=4,option_combination_pattern="2-1-4-3"),
 r(91,"History","Medieval",MCQ,"medium","specialized reference","Which is NOT written by Tulsidas (Sahitya Lahari)"),
 r(92,"History","Medieval",MT,"hard","specialized reference","Match building with builder (Kabuli Bagh Mosque, Adhai Din Ka Jhopra, Allahabad Fort, Itmad-ud-Daulah)",list_item_count=4),
 r(93,"History","Modern",MCQ,"medium","specialized reference","Which is NOT correctly matched (person-associated) (James A. Hicky-Calcutta Chronicle)"),
 r(94,"History","Medieval",MT,"hard","specialized reference","Match Mughal father with son (Babar, Akbar, Shah Jahan, Jahangir)",list_item_count=4),
 r(95,"History","Ancient",MCQ,"medium","NCERT-level","Which Buddhist council was NOT held in Bihar (Fourth)",ambiguous_subject="TRUE",ambiguous_note="Bihar-linked"),
 r(96,"History","Modern",ST,"medium","specialized reference","Subhas Chandra Bose statements — which correct (Deleted)",statement_count=3),
 r(97,"History","Ancient",MCQ,"medium","specialized reference","Who was NOT an Acharya at Nalanda (Kautilya)",ambiguous_subject="TRUE",ambiguous_note="Nalanda is in Bihar"),
 r(98,"History","Modern",ST,"hard","specialized reference","Chronological order (Nand Kumar, Salbai, Wandiwash, Tipu death)",statement_count=4,option_combination_pattern="3-1-2-4"),
 r(99,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","First-published newspaper of Bihar (Patna Harkara)"),
 r(100,"Bihar-Specific","History & Culture",MT,"hard","specialized reference","Match Bihar event/org with person (Champaran, Azad Dasta, Individual Satyagraha, Kisan Sabha)",list_item_count=4),
 r(101,"Geography","World",MCQ,"easy","NCERT-level","Maginot Line exists between which countries (France & Germany)"),
 r(102,"Geography","World",MCQ,"easy","NCERT-level","Strait of Hormuz connects (Persian Gulf to Gulf of Oman)"),
 r(103,"Geography","World",MCQ,"easy","NCERT-level","Where is 'Ground Zero' (New York)"),
 r(104,"Geography","World",MCQ,"medium","specialized reference","Isthmus known as 'Devil's Neck' (Isthmus of Panama)"),
 r(105,"Geography","Human",MCQ,"medium","NCERT-level","Ladang refers to (Shifting Agriculture)"),
 r(106,"Geography","Physical",MCQ,"easy","NCERT-level","Largest river island in the world (Majuli)"),
 r(107,"Geography","Physical",MCQ,"medium","NCERT-level","Second largest river basin of India (final key: Narmada)"),
 r(108,"Geography","Physical",MCQ,"medium","NCERT-level","Confluence of Alaknanda and Bhagirathi (Devprayag)"),
 r(109,"Geography","Physical",MCQ,"medium","NCERT-level","Two volcanic islands in Indian Territory (Narcondam and Barren)"),
 r(110,"Current Affairs","National",MCQ,"medium","current_affairs","Meerut GI-tag item (Scissors)",ambiguous_subject="TRUE",ambiguous_note="GI tag — could be Geography/Economic"),
 r(111,"Environment & Ecology","Conservation & Policy",MCQ,"medium","specialized reference","Temperate Forest Research Centre city (Shimla)"),
 r(112,"Environment & Ecology","Biodiversity",MCQ,"easy","NCERT-level","Kanha National Park is in (Madhya Pradesh)"),
 r(113,"Geography","Physical",MCQ,"easy","NCERT-level","'Loktak' is a (Lake)"),
 r(114,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Parks under Project Tiger in Bihar (Valmiki National Park)",ambiguous_subject="TRUE",ambiguous_note="could be Environment"),
 r(115,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","State animal of Bihar (Bull/Ox)"),
 r(116,"Bihar-Specific","Recent Developments",MCQ,"medium","specialized reference","Year Nalanda University re-established in Bihar (2014)"),
 r(117,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Karmanasa river originates in (Kaimur District)"),
 r(118,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Bihar produces __% of India's pyrite (Deleted)"),
 r(119,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Gold found in which district of Bihar (Jamui)"),
 r(120,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Climate type of most of Bihar (Subtropical Monsoon)"),
 r(121,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Marginal friction force on box at constant velocity (200 N)"),
 r(122,"Science & Technology","Physics",MCQ,"hard","specialized reference","Force on truck (final key: 13000 N)"),
 r(123,"Science & Technology","Physics",MCQ,"medium","NCERT-level","250 units of energy in Joule (9x10^8)"),
 r(124,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Medium with maximum speed of sound (Steel)"),
 r(125,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Freely falling body PE decreases — energy conservation not violated"),
 r(126,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Work done by oxen ploughing (2100 Joule)"),
 r(127,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Focal distance of a plane mirror (Infinity)"),
 r(128,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Which term does NOT denote electric power (IR^2)"),
 r(129,"Science & Technology","Physics",MCQ,"easy","NCERT-level","In short circuit, electric current (increases very high)"),
 r(130,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Device to protect equipment from electric shock (Fuse)"),
 r(131,"Science & Technology","Chemistry",MCQ,"easy","NCERT-level","pH of 0.1 N HCl solution (1.0)"),
 r(132,"Science & Technology","Chemistry",MCQ,"hard","specialized reference","Compound known as night-glowing pigment (Europium doped strontium aluminate)"),
 r(133,"Science & Technology","Tech & Innovation",MCQ,"hard","specialized reference","Material used for smart film (Indium tin oxide)"),
 r(134,"Science & Technology","Chemistry",MCQ,"hard","specialized reference","Metal compound used for carcinoma treatment (Platinum)"),
 r(135,"Science & Technology","Chemistry",MCQ,"medium","specialized reference","Compound used in contraceptive pills (Levonorgestrel)"),
 r(136,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Why oil is not stored in galvanized iron pot (All of above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(137,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Compound used to increase octane rating (Tetraethyllead)"),
 r(138,"Science & Technology","Chemistry",MCQ,"hard","specialized reference","Full form of PHBV biodegradable polymer"),
 r(139,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Hormones are secreted by (Endocrine glands)"),
 r(140,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Herpes simplex virus-human interaction (Parasitism)"),
 r(141,"Science & Technology","Biology",MCQ,"medium","specialized reference","First immunoglobulin produced in response to infection (IgM)"),
 r(142,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Biological membranes composed of (lipids and proteins)"),
 r(143,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Which is a non-sense codon (UAA)"),
 r(144,"Environment & Ecology","Biodiversity",MCQ,"easy","NCERT-level","Species in danger of extinction known as (Endangered)"),
 r(145,"Geography","Economic",MCQ,"easy","NCERT-level","Which is a Kharif crop (Sugarcane)"),
 r(146,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Xylem in plants is responsible for (transport of water/minerals)"),
 r(147,"Science & Technology","Biology",MCQ,"hard","specialized reference","Who first used vascular tissue in plant classification (A.P. de Candolle)"),
 r(148,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Part we eat in Mango (Mesocarp)"),
 r(149,"Environment & Ecology","Climate & Pollution",MCQ,"easy","NCERT-level","Ozone Day celebrated on (16 September)"),
 r(150,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Advantage of plant in mycorrhizal association (increased mineral absorption)"),
]

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "71st.csv")
    n = write_rows(ROWS, out)
    print(f"wrote {n} rows -> {out}")
