"""70th BPSC Prelims RE-EXAM (4 Jan 2025), Set I, 4-option. Provisional key.
Tagged from English. correct_option auto-filled from official Set-I key.
"""
import os
from schema import COLUMNS, write_rows

KEY = {1:"B",2:"A",3:"A",4:"C",5:"B",6:"D",7:"C",8:"C",9:"B",10:"D",11:"A",12:"B",13:"Deleted",14:"C",15:"D",
16:"D",17:"B",18:"D",19:"B",20:"C",21:"A",22:"A",23:"D",24:"B",25:"D",26:"A",27:"C",28:"B",29:"C",30:"B",
31:"A",32:"B",33:"C",34:"A",35:"B",36:"C",37:"B",38:"D",39:"B",40:"D",41:"B",42:"B",43:"B",44:"A",45:"B",
46:"B",47:"A",48:"A",49:"D",50:"D",51:"B",52:"C",53:"A",54:"B",55:"A",56:"C",57:"D",58:"C",59:"B",60:"D",
61:"D",62:"B",63:"A",64:"D",65:"C",66:"A",67:"A",68:"B",69:"D",70:"D",71:"B",72:"B",73:"B",74:"B",75:"A",
76:"D",77:"A",78:"A",79:"Deleted",80:"A",81:"D",82:"B",83:"B",84:"A",85:"C",86:"A",87:"D",88:"A",89:"A",90:"D",
91:"Deleted",92:"C",93:"B",94:"B",95:"C",96:"B",97:"D",98:"B",99:"B",100:"D",101:"A",102:"C",103:"A",104:"A",105:"D",
106:"B",107:"A",108:"A",109:"B",110:"B",111:"A",112:"C",113:"B",114:"A",115:"B",116:"C",117:"D",118:"A",119:"C",120:"D",
121:"A",122:"B",123:"B",124:"A",125:"D",126:"B",127:"A",128:"C",129:"C",130:"A",131:"A",132:"B",133:"D",134:"A",135:"D",
136:"B",137:"A",138:"B",139:"A",140:"D",141:"C",142:"D",143:"B",144:"A",145:"C",146:"B",147:"C",148:"C",149:"A",150:"C"}

DEF = dict(year="70th-reexam", exam_date="2025-01-04", paper_variant="re-exam", booklet_series="I",
           option_count=4, key_status="provisional", statement_count="", list_item_count="",
           option_combination_pattern="", is_all_or_none_correct="FALSE",
           all_none_literal_phrasing="FALSE", ambiguous_subject="FALSE", ambiguous_note="",
           ca_recency_months="")

def r(qn, subject, sub, qtype, diff, src, text, **kw):
    row = dict(DEF); row.update(kw)
    row.update(question_number=qn, subject=subject, sub_topic=sub, question_type=qtype,
               difficulty_guess=diff, source_type_guess=src, question_text_en=text,
               correct_option=KEY[qn])
    return row

ST, MT, MCQ, AR, RA = "statement_based", "match_the_following", "simple_mcq", "assertion_reason", "reasoning_aptitude"
ROWS = [
 r(1,"History","Ancient",MCQ,"easy","NCERT-level","Oldest civilization in the world (Mesopotamia)"),
 r(2,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Condition for two liquids to form an ideal solution (enthalpy of mixing zero)"),
 r(3,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Number series 117, 98, 80, 64, ?, 42 (51)"),
 r(4,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","First elected Chairman of Bihar Legislative Council under GoI Act 1935 (Rajiv Ranjan Sinha)"),
 r(5,"Geography","Physical",MCQ,"hard","specialized reference","River pair cutting Tropic of Cancer twice over Chhota Nagpur (North Koel-Suwarnarekha)"),
 r(6,"Economy","Macroeconomic concepts",MCQ,"medium","NCERT-level","Sector that benefitted most from Globalization (Services)"),
 r(7,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Antibodies produced against vaccine antigens (by only B cells)"),
 r(8,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","SC power to decide Centre-State disputes (Original jurisdiction)"),
 r(9,"History","Modern",MCQ,"hard","specialized reference","Newspaper that called INC 'nucleus of future Parliament' (The Indian Mirror)"),
 r(10,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Count triangles in the figure (12)"),
 r(11,"Geography","Physical",MCQ,"medium","specialized reference","State with the longest boundary with Madhya Pradesh (Uttar Pradesh)"),
 r(12,"History","Modern",MCQ,"easy","NCERT-level","Who led the Champaran Satyagraha 1917 (Mahatma Gandhi)",ambiguous_subject="TRUE",ambiguous_note="Champaran is in Bihar"),
 r(13,"Geography","Physical",MCQ,"easy","NCERT-level","Tropic of Cancer passes through which State (Deleted)"),
 r(14,"Current Affairs","Awards & Appointments",MCQ,"easy","current_affairs","Bharat Ratna 2024 recipient (M.S. Swaminathan)",ca_recency_months=11),
 r(15,"Science & Technology","Physics",MCQ,"medium","NCERT-level","X-rays can be deflected by (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(16,"Environment & Ecology","Conservation & Policy",ST,"easy","NCERT-level","Renewable Energy means (solar, wind)",statement_count=4,option_combination_pattern="1 and 4 only"),
 r(17,"Bihar-Specific","Polity & Governance",MCQ,"medium","specialized reference","Act converting Bihar to bicameral legislature (GoI Act 1919)"),
 r(18,"Geography","World",MCQ,"hard","specialized reference","Oldest mountain of South America (Pacaraima)"),
 r(19,"Polity","Constitutional provisions",ST,"hard","NCERT-level","Amendments needing ratification by >=half states",statement_count=4,option_combination_pattern="1, 2 and 3"),
 r(20,"History","Modern",MCQ,"medium","NCERT-level","State NOT annexed under Doctrine of Lapse (Jaipur)"),
 r(21,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Bihar district with maximum wheat production (Rohtas)"),
 r(22,"Current Affairs","Sports",MCQ,"easy","specialized reference","Most popular field game in the world (Soccer)",ambiguous_subject="TRUE",ambiguous_note="static GK"),
 r(23,"History","Modern",MCQ,"medium","NCERT-level","Author of 'Poverty and Un-British Rule in India' 1901 (Dadabhai Naoroji)"),
 r(24,"History","Modern",MCQ,"medium","specialized reference","Fort William College Calcutta established (1800, civil servants in Indian languages)"),
 r(25,"History","Ancient",MCQ,"easy","NCERT-level","Script on Ashoka's Pillars (Brahmi)"),
 r(26,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Catalyst in hydrogenation of vegetable oil (Ni)"),
 r(27,"Geography","Economic",MCQ,"medium","NCERT-level","Grey revolution is related to (Fertilizers)"),
 r(28,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","Article dealing with proclamation of Emergency (352)"),
 r(29,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Sufi Silsilah founded in Bihar (Firdousia)"),
 r(30,"Current Affairs","International",MCQ,"easy","specialized reference","Which country is NOT a member of G7 (Russia)"),
 r(31,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Site of dark reaction in photosynthesis (Stroma)"),
 r(32,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Direction-distance: Raj X to Y (30 metres)"),
 r(33,"History","Ancient",MCQ,"medium","specialized reference","Deogarh temple + Garhwa sculptures are remains of (Gupta art)"),
 r(34,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Bihar produces 71% of India's annual production of (Lychee)"),
 r(35,"Current Affairs","International",MCQ,"easy","current_affairs","City where G20 Summit 2023 held in India (New Delhi)",ca_recency_months=16),
 r(36,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Why moon has no atmosphere (escape velocity < rms velocity)"),
 r(37,"History","Ancient",MCQ,"easy","NCERT-level","Founder of the Maurya Empire (Chandragupta Maurya)"),
 r(38,"History","Ancient",MCQ,"medium","NCERT-level","NOT a famous Buddhist learning centre in Ancient India (Nagpur)"),
 r(39,"Current Affairs","International",MCQ,"easy","current_affairs","Country that hosted 2023 World Economic Forum meeting (Switzerland)",ca_recency_months=23),
 r(40,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Which vitamins are water soluble (None of these)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(41,"History","Modern",MCQ,"medium","specialized reference","INC President after Bose resigned 1939 (provisional key: Abul Kalam Azad)"),
 r(42,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Clock: hands together between 2 and 3 (10 10/11 past 2)"),
 r(43,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Amendment deciding max State Council of Ministers strength (91st)"),
 r(44,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Anopheles mosquito also a vector of (Encephalitis and Filariasis)"),
 r(45,"Current Affairs","International",MCQ,"easy","current_affairs","Re-elected President of France 2022 (Emmanuel Macron)",ca_recency_months=33),
 r(46,"Economy","Five-year plans & policy",MCQ,"medium","NCERT-level","Correct pair: First Five-Year Plan - Focus on Agriculture"),
 r(47,"Geography","World",MCQ,"hard","specialized reference","Mountain range along Mediterranean Coast of Asia Minor (Taurus)"),
 r(48,"Current Affairs","Sports",MCQ,"medium","current_affairs","Country to host 20th Asian Games 2026 (Japan)"),
 r(49,"Current Affairs","Sports",MCQ,"easy","current_affairs","Country that hosted 2022 Winter Olympics (China)",ca_recency_months=35),
 r(50,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Turmeric powder obtained from which part (Dried root)"),
 r(51,"History","Modern",MCQ,"medium","specialized reference","Viceroy who decentralized colonial economic structure (Mayo)"),
 r(52,"Geography","World",MCQ,"easy","NCERT-level","'Playground of Europe' (Switzerland)"),
 r(53,"History","Modern",MCQ,"medium","NCERT-level","Where did the revolt of Birsa Munda take place (Ranchi)"),
 r(54,"Current Affairs","National",MCQ,"medium","current_affairs","First Indian company to cross USD 200bn market cap 2023 (Reliance)",ambiguous_subject="TRUE",ambiguous_note="could be Economy"),
 r(55,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Reactance of a capacitor (inversely proportional to frequency)"),
 r(56,"Economy","Five-year plans & policy",MCQ,"easy","NCERT-level","Max land an individual farmer can hold (Land ceiling)"),
 r(57,"History","Modern",MCQ,"medium","specialized reference","The Vernacular Press Act allowed (More than one of the above)"),
 r(58,"Bihar-Specific","Geography",MCQ,"hard","specialized reference","Average height of Kosi Plain from MSL (30 m)"),
 r(59,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","Chairperson of the GST Council (Union Finance Minister)"),
 r(60,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","When was Bihar State formed (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(61,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Sour taste of vinegar due to (provisional key: Citric acid)"),
 r(62,"History","Medieval",MCQ,"medium","specialized reference","'Muqaddam/Chaudhuri' in Delhi Sultanate used for (Village headmen)"),
 r(63,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Nobel Peace Prize 2023 winner (Narges Mohammadi)",ca_recency_months=15),
 r(64,"History","Medieval",MCQ,"hard","specialized reference","'Tarikh-i-Firuz Shahi' written by (provisional key: Minhaj Siraj)"),
 r(65,"Geography","World",MCQ,"easy","NCERT-level","Odd pair among deserts (Kalahari:America)",ambiguous_subject="TRUE",ambiguous_note="odd-one-out — Reasoning element"),
 r(66,"Science & Technology","Chemistry",MCQ,"medium","specialized reference","How is Hydrogen stored physically (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(67,"History","Modern",MCQ,"medium","specialized reference","Portfolio Rajendra Prasad held in interim govt 1946 (Food and agriculture)",ambiguous_subject="TRUE",ambiguous_note="Rajendra Prasad — Bihar figure"),
 r(68,"Geography","Economic",MCQ,"hard","specialized reference","Oil refinery with maximum capacity in India (provisional key: Barauni)",ambiguous_subject="TRUE",ambiguous_note="Barauni is in Bihar"),
 r(69,"Polity","Panchayati Raj & local governance",MCQ,"easy","NCERT-level","System of governance in Panchayat Raj (three-tier)"),
 r(70,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Blood group of an individual determined by (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(71,"Current Affairs","Sports",MCQ,"medium","current_affairs","Game NOT included in 33rd Olympic (Cricket)",ca_recency_months=5),
 r(72,"Geography","Physical",MCQ,"easy","NCERT-level","'Scotland of North-East India' (Meghalaya)"),
 r(73,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","Schedule with Anti-defection Act provisions (Tenth)"),
 r(74,"Science & Technology","Tech & Innovation",MCQ,"medium","specialized reference","First 3D-printed humanoid robot in India (Manav)"),
 r(75,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Article for Annual Financial Statement before Parliament (112)"),
 r(76,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","60.2% share in Bihar GSDP 2019-20 was of (Service Sector)"),
 r(77,"Bihar-Specific","Geography",MCQ,"easy","specialized reference","Bihar district with maximum Lichi production (Muzaffarpur)"),
 r(78,"Bihar-Specific","Geography",MCQ,"easy","specialized reference","River known as 'Sorrow of Bihar' (provisional key: Son)"),
 r(79,"Geography","Physical",MCQ,"medium","specialized reference","Average height of snow-line in Uttar Pradesh (Deleted)"),
 r(80,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Ishihara test is related with (Colour blindness)"),
 r(81,"History","Modern",MCQ,"medium","specialized reference","Who is NOT associated with Azad Hind Fauj (S.A. Dange)"),
 r(82,"Economy","Macroeconomic concepts",MCQ,"medium","NCERT-level","What is Infant Mortality Rate (die before age 1 per 1000)"),
 r(83,"Geography","World",MCQ,"hard","specialized reference","Longitude separating Canada and Alaska (141 W)"),
 r(84,"History","Modern",MT,"hard","specialized reference","Match authors with books on 1857 (Savarkar, S.N. Sen, Eric Stokes, S.B. Chaudhuri)",list_item_count=4),
 r(85,"History","Modern",MT,"medium","NCERT-level","Match social reformers with societies (Brahmo Samaj, Ramkrishna Mission, Servants of India, Vidhwa Vivah Samaj)",list_item_count=4),
 r(86,"Science & Technology","Tech & Innovation",MCQ,"medium","NCERT-level","Fibre used in bullet-proof helmets/jackets (Kevlar)"),
 r(87,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Speaker of Lok Sabha voting right (only in case of a tie)"),
 r(88,"History","Medieval",MCQ,"hard","specialized reference","Term 'Zillillah' first used by (Alauddin Khilji)"),
 r(89,"Economy","Banking & finance",MCQ,"easy","NCERT-level","Ratio of deposits banks must keep with RBI (Cash Reserve Ratio)"),
 r(90,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Final energy of electron through potential difference V (eV)"),
 r(91,"Current Affairs","Schemes & Indices",MCQ,"medium","current_affairs","Indian State with highest literacy rate per 2023 census (Kerala)"),
 r(92,"History","Ancient",MCQ,"hard","specialized reference","NOT associated with Chandragupta Maurya (Junagadh inscription of Rudradaman)"),
 r(93,"Current Affairs","Schemes & Indices",MCQ,"medium","current_affairs","State that topped NITI Aayog SDG India Index 2023 (Kerala)",ca_recency_months=15),
 r(94,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Buds are typically found (both base of leaves and tip of branches)"),
 r(95,"Polity","Constitutional provisions",MCQ,"hard","NCERT-level","Electoral college for President but not impeachment forum (State Legislative Assemblies)"),
 r(96,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Amarkantak source of Son river situated at (Maikal range)"),
 r(97,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Coding-decoding: CIRCLE:RICELC :: SQUARE:? (AREUQS)"),
 r(98,"Science & Technology","Chemistry",MCQ,"hard","specialized reference","Which is NOT an electrophile (Na+)"),
 r(99,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Parliament law for International treaties (without consent of any State)"),
 r(100,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Bihar district with maximum Maize production (Saran)"),
 r(101,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Quinine obtained from which part of plant (Stem bark)"),
 r(102,"History","Modern",MCQ,"medium","specialized reference","First Muslim President of INC (Badruddin Taiyabji)"),
 r(103,"Geography","Physical",MCQ,"medium","NCERT-level","Kashmir Valley is which type of valley (Tectonic)"),
 r(104,"History","Modern",MCQ,"medium","specialized reference","When Macaulay issued famous minute on Indian Education (02 Feb 1835)"),
 r(105,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Calendar: Jan 1 2008 Tue -> day on Jan 1 2009 (Thursday)"),
 r(106,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Conductivity of a strong electrolyte on dilution (decreases)"),
 r(107,"History","Modern",MCQ,"medium","NCERT-level","Santhal hool (rebellion) took place in (1855-56)"),
 r(108,"Current Affairs","Awards & Appointments",MCQ,"easy","current_affairs","Current Chairman of ISRO (S. Somnath)",ca_recency_months=30),
 r(109,"Geography","World",MCQ,"medium","specialized reference","NOT associated with Australia Continent (Salwin Mountain)"),
 r(110,"Environment & Ecology","Climate & Pollution",MCQ,"easy","current_affairs","Country that hosted COP28 climate summit 2023 (UAE)",ca_recency_months=13),
 r(111,"Science & Technology","Tech & Innovation",MCQ,"medium","current_affairs","Number of scientific payloads on Aditya L-1 mission (7)",ca_recency_months=15),
 r(112,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Program Bihar Education Dept started via DD Bihar Apr 2020 (e-content class IX-X)"),
 r(113,"History","Modern",MCQ,"medium","specialized reference","All India Trade Union Congress formed in the year (1920)"),
 r(114,"Science & Technology","Physics",MCQ,"medium","NCERT-level","As telescope objective lens diameter increases, resolution (increases)"),
 r(115,"Current Affairs","International",MCQ,"easy","current_affairs","Prime Minister of Italy as of 2024 (Giorgia Meloni)",ca_recency_months=27),
 r(116,"Current Affairs","National",MCQ,"medium","current_affairs","First Indian city declared 'City of Literature' by UNESCO (Kozhikode)",ca_recency_months=19),
 r(117,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","World famous painting found in which district of Bihar (Madhubani)"),
 r(118,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Right a British citizen in India can NOT claim (Freedom of trade and profession)"),
 r(119,"History","Modern",MCQ,"medium","NCERT-level","Who introduced permanent settlement in Bengal (Lord Cornwallis)"),
 r(120,"History","Modern",MCQ,"medium","NCERT-level","Who threw harmless bombs in Central Legislative Assembly (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(121,"Science & Technology","Chemistry",MCQ,"hard","specialized reference","Seed used in production of engineered diamonds (Moissanite)"),
 r(122,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Bihar district with highest fox nut (makhana) production (Madhubani)"),
 r(123,"History","Modern",MCQ,"medium","specialized reference","Author of the book 'Gulamgiri' (Jyotiba Phule)"),
 r(124,"Geography","World",MCQ,"medium","specialized reference","Dalmatian Coast is (River depositional)"),
 r(125,"Economy","Banking & finance",MCQ,"easy","NCERT-level","Function of Central Bank (All of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(126,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Nail nailed into tree trunk after 2 years will (remain at same position)"),
 r(127,"History","Modern",MT,"hard","specialized reference","Match 1857 leaders with territory (Kunwar Singh, Hazrat Mahal, Khan Bahadur, Maulvi Ahmadullah)",list_item_count=4),
 r(128,"History","Ancient",MCQ,"medium","NCERT-level","Indus Valley city with trade with West Asia (Lothal)"),
 r(129,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Responsible for production of shadow (Rectilinear propagation of light)"),
 r(130,"History","Modern",MCQ,"medium","specialized reference","President of INC at Gaya Session 1922 (Chittaranjan Das)",ambiguous_subject="TRUE",ambiguous_note="Gaya session — Bihar-linked"),
 r(131,"Current Affairs","Schemes & Indices",MCQ,"easy","current_affairs","Expanded form of UPI (Unified Payment Interface)"),
 r(132,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Liver stores which vitamins (A, B, C and D)"),
 r(133,"Geography","Economic",MCQ,"medium","specialized reference","State of India called 'State of Minerals' (Jharkhand)"),
 r(134,"History","Ancient",MCQ,"medium","specialized reference","Chitrakoot temple is located in which State (Madhya Pradesh)",ambiguous_subject="TRUE",ambiguous_note="could be Geography"),
 r(135,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Min age for MP Lok Sabha, MP Rajya Sabha, President (25, 30 and 35)"),
 r(136,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Unit of measure of magnetic field (Tesla)"),
 r(137,"Current Affairs","Awards & Appointments",MCQ,"hard","specialized reference","President of India + Ambassador to USA/China/Turkey/Thailand + JNU VC (R. Venkatraman)"),
 r(138,"Geography","Physical",MCQ,"medium","specialized reference","Divi Island situated amid distributaries of which river (Krishna)"),
 r(139,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Venn diagram: Men that are both Businessman and Millionaire (3)"),
 r(140,"Economy","Macroeconomic concepts",MCQ,"medium","NCERT-level","Which is a tool of Fiscal Policy (Taxes)"),
 r(141,"Environment & Ecology","Conservation & Policy",MCQ,"medium","current_affairs","Steam methane reforming technique used to obtain (Grey Hydrogen)",ambiguous_subject="TRUE",ambiguous_note="could be Sci & Tech"),
 r(142,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Primary function of Finance Commission (distribution of revenue Centre-States)"),
 r(143,"History","Modern",MCQ,"medium","NCERT-level","Who first called Revolt of 1857 'First Indian War of Independence' (V.D. Savarkar)"),
 r(144,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Blood relation puzzle: A is (Wife of D)"),
 r(145,"Science & Technology","Chemistry",MCQ,"hard","specialized reference","Reducing power order of metals by electrode potential (B>C>A)"),
 r(146,"Economy","Macroeconomic concepts",MCQ,"medium","NCERT-level","NNP at factor cost is equal to (National Income)"),
 r(147,"History","Modern",MT,"hard","specialized reference","Match Pre-Congress organisations with leaders (Indian Association, Madras Mahajan Sabha, Bombay Presidency Assoc, Poona Sarvjanik Sabha)",list_item_count=4),
 r(148,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Burn from steam vs air at 100C (more dangerous, high latent heat)"),
 r(149,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","15 chairs in a row, P at middle, Q at 12th from right — chairs between (2)"),
 r(150,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","When was Patna College established (1863)"),
]

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "70th_re.csv")
    n = write_rows(ROWS, out)
    print(f"wrote {n} rows -> {out}")
