"""70th BPSC Prelims (13 Dec 2024), Set E, 4-option. Provisional key.
Tagged from English (official standard). correct_option auto-filled from official Set-E key.
"""
import os
from schema import COLUMNS, write_rows

KEY = {1:"D",2:"B",3:"B",4:"A",5:"B",6:"A",7:"C",8:"B",9:"A",10:"B",11:"B",12:"B",13:"C",14:"C",15:"A",
16:"C",17:"A",18:"C",19:"D",20:"C",21:"C",22:"B",23:"C",24:"B",25:"C",26:"C",27:"A",28:"C",29:"C",30:"C",
31:"D",32:"D",33:"D",34:"D",35:"D",36:"A",37:"D",38:"B",39:"B",40:"A",41:"D",42:"A",43:"B",44:"A",45:"B",
46:"A",47:"D",48:"B",49:"B",50:"A",51:"D",52:"C",53:"D",54:"B",55:"D",56:"B",57:"C",58:"C",59:"C",60:"D",
61:"B",62:"B",63:"B",64:"B",65:"C",66:"B",67:"A",68:"C",69:"B",70:"A",71:"C",72:"A",73:"A",74:"B",75:"A",
76:"C",77:"A",78:"D",79:"A",80:"A",81:"D",82:"C",83:"A",84:"A",85:"B",86:"C",87:"C",88:"A",89:"C",90:"B",
91:"B",92:"C",93:"D",94:"D",95:"B",96:"A",97:"B",98:"B",99:"D",100:"C",101:"A",102:"C",103:"A",104:"C",105:"C",
106:"C",107:"A",108:"B",109:"A",110:"D",111:"B",112:"A",113:"B",114:"C",115:"A",116:"D",117:"B",118:"A",119:"D",120:"A",
121:"D",122:"A",123:"B",124:"C",125:"D",126:"B",127:"B",128:"B",129:"B",130:"B",131:"A",132:"D",133:"A",134:"C",135:"C",
136:"A",137:"D",138:"C",139:"B",140:"A",141:"B",142:"D",143:"B",144:"D",145:"A",146:"D",147:"C",148:"C",149:"C",150:"B"}

DEF = dict(year="70th", exam_date="2024-12-13", paper_variant="main", booklet_series="E",
           option_count=4, key_status="provisional", statement_count="", list_item_count="",
           option_combination_pattern="", is_all_or_none_correct="FALSE",
           all_none_literal_phrasing="FALSE", ambiguous_subject="FALSE", ambiguous_note="",
           ca_recency_months="")

def r(qn, subject, sub, qtype, diff, src, text, **kw):
    row = dict(DEF); row.update(kw)
    row.update(question_number=qn, subject=subject, sub_topic=sub, question_type=qtype,
               difficulty_guess=diff, source_type_guess=src, question_text_en=text,
               correct_option=KEY[qn])
    return row

ST, MT, MCQ, AR, RA = "statement_based", "match_the_following", "simple_mcq", "assertion_reason", "reasoning_aptitude"
ROWS = [
 r(1,"Geography","Economic",MCQ,"medium","NCERT-level","Which is an iron ore (Bauxite/Cinnabar/Pyrite/Limonite)",ambiguous_subject="TRUE",ambiguous_note="minerals — could be Sci & Tech/Chemistry"),
 r(2,"Geography","Physical",MCQ,"easy","NCERT-level","Rock formed from cooling/solidifying lava (Igneous)"),
 r(3,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Object of 'cut motion' in Parliament"),
 r(4,"History","Modern",MCQ,"easy","NCERT-level","When British shifted capital to Delhi (1912)"),
 r(5,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Anglo-Indian representation in Lok Sabha (104th CAA)"),
 r(6,"Current Affairs","International",MCQ,"medium","current_affairs","Venue of 13th WTO Ministerial Feb 2024 (Abu Dhabi)",ca_recency_months=10,ambiguous_subject="TRUE",ambiguous_note="could be Economy"),
 r(7,"Current Affairs","Sports",MCQ,"medium","current_affairs","French Open 2024 Men's Singles winner (Alcaraz)",ca_recency_months=6),
 r(8,"Current Affairs","National",MCQ,"hard","current_affairs","Postal-ballot age after Mar 2024 change (85)",ca_recency_months=9,ambiguous_subject="TRUE",ambiguous_note="could be Polity"),
 r(9,"Economy","Five-year plans & policy",MCQ,"hard","current_affairs","Budget 2024-25 oilseed NOT under Atmanirbharta (Coconut)",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(10,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Which pairs give displacement reactions (AgNO3 + copper)"),
 r(11,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Bihula Festival — which Bihar district (Bhagalpur)"),
 r(12,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Heat transfer needing no medium (Radiation)"),
 r(13,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Which acid is secreted in the stomach (Hydrochloric)"),
 r(14,"History","Modern",MCQ,"medium","NCERT-level","Ramkrishna Mission founded by (Swami Vivekanand, 1897)"),
 r(15,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Bihar city with new National Dolphin Research Centre (Patna)"),
 r(16,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Article restricting MP from holding office of profit (102(1)(a))"),
 r(17,"Current Affairs","International",MCQ,"medium","current_affairs","First country to bring soil from far side of moon, June 2024 (China)",ca_recency_months=6,ambiguous_subject="TRUE",ambiguous_note="could be Sci & Tech"),
 r(18,"Geography","Physical",ST,"medium","NCERT-level","Mountain ranges east-to-west sequence (Garo, Nandadevi, Kamet, K2)",statement_count=4,option_combination_pattern="1 2 3 4"),
 r(19,"Polity","Constitutional provisions",MCQ,"medium","specialized reference","Speaker of Lok Sabha before becoming President (Neelam Sanjeeva Reddy)",ambiguous_subject="TRUE",ambiguous_note="static GK"),
 r(20,"History","Modern",MCQ,"easy","NCERT-level","Who gave the slogan 'Do or Die' and when (Gandhi, Quit India)"),
 r(21,"Current Affairs","National",MCQ,"medium","current_affairs","When CANI undersea cable project inaugurated (Aug 10, 2020)",ca_recency_months=52),
 r(22,"History","Modern",MCQ,"medium","specialized reference","Who wrote 'New Lamps For The Old' (Aurobindo Ghosh)"),
 r(23,"Current Affairs","National",MCQ,"medium","current_affairs","LS seat where Shompen PVTG first voted Apr 2024 (Andaman & Nicobar)",ca_recency_months=8),
 r(24,"Current Affairs","International",MCQ,"easy","current_affairs","Country that joined NATO Mar 2024 after 200 yrs neutral (Sweden)",ca_recency_months=9),
 r(25,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Meter to measure distance moved by a vehicle (Odometer)"),
 r(26,"History","Modern",MCQ,"medium","NCERT-level","When Muslim League observed 'Direct Action Day' (16 Aug 1946)"),
 r(27,"Current Affairs","National",MCQ,"medium","current_affairs","India's position in mobile phone manufacturing 2023 (2nd)",ambiguous_subject="TRUE",ambiguous_note="could be Economy"),
 r(28,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","Two words added to Preamble by 42nd Amendment (Secular, Socialist)"),
 r(29,"Science & Technology","Physics",MCQ,"medium","NCERT-level","First to propose a model for atomic structure (J.J. Thomson)"),
 r(30,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","IIP FY2023 — which indices grew significantly (capital + infra goods)",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(31,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Amendment restricting Council of Ministers to 15% of Lok Sabha (91st)"),
 r(32,"Current Affairs","International",MCQ,"medium","current_affairs","Apr 2024 UNSC members who rejected/abstained on Palestine UN membership (3)",ca_recency_months=8),
 r(33,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Ruchira Kamboj (first woman Indian Ambassador to UN) — which is true",ca_recency_months=3),
 r(34,"Science & Technology","Chemistry",ST,"medium","NCERT-level","Dalton's atomic theory explained which laws",statement_count=4,option_combination_pattern="i, ii and iv"),
 r(35,"History","Ancient",ST,"hard","specialized reference","King 'Praversena' (Vakataka) statements — which correct",statement_count=4,option_combination_pattern="More than one of the above"),
 r(36,"Polity","Panchayati Raj & local governance",MCQ,"medium","NCERT-level","Art 243J — who provides for maintenance of Panchayat accounts (State Legislature)"),
 r(37,"Environment & Ecology","Conservation & Policy",MCQ,"medium","specialized reference","Full form of PCRA (Petroleum Conservation Research Association)",ambiguous_subject="TRUE",ambiguous_note="organisation GK — could be Economy"),
 r(38,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Who decides disqualification of MLAs (non-10th-schedule matters) (Governor)"),
 r(39,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Bacterial disease called spleenic fever (Anthrax)"),
 r(40,"Geography","Physical",MCQ,"medium","NCERT-level","Which river is different from the others (Narmada)",ambiguous_subject="TRUE",ambiguous_note="odd-one-out — Reasoning element"),
 r(41,"Geography","Human",MCQ,"easy","NCERT-level","Cause of rural-to-urban migration in India (All the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(42,"History","Modern",MCQ,"medium","specialized reference","Founder of the Farazi Movement (Haji Shariatullah)"),
 r(43,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Newspaper Sahajanand Saraswati published for peasants (Lok Sangraha)",ambiguous_subject="TRUE",ambiguous_note="could be Modern History"),
 r(44,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Group of letters different from others (PSVX/ORUX/JMPS/CFIL)"),
 r(45,"Economy","Banking & finance",MCQ,"hard","current_affairs","CRISIL: corporate bond market size by FY2030 (Rs 100-120 lakh cr)",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(46,"History","Modern",MT,"medium","specialized reference","Match political organisation with founder (Khaksars, Socialist Party, ILP, Forward Bloc)",list_item_count=4),
 r(47,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Shreyasi Singh (shooter MLA) elected from which Bihar constituency (Jamui)",ca_recency_months=5),
 r(48,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Justice N. Kotiswar Singh was CJ of which HC before SC (J&K and Ladakh)",ca_recency_months=5),
 r(49,"Bihar-Specific","Geography",MCQ,"hard","specialized reference","Bihar district with highest % ST population (2011 census)"),
 r(50,"Science & Technology","Chemistry",ST,"medium","NCERT-level","Which processes are exothermic (evaporation, acid dilution, quicklime, sublimation)",statement_count=4,option_combination_pattern="ii and iii"),
 r(51,"Bihar-Specific","Geography",MT,"medium","specialized reference","Match Bihar districts with products (Vaishali, Bhagalpur, Jamui, Madhepura)",list_item_count=4),
 r(52,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Analogy: Motorcycle:battery :: Life:? (Sun)"),
 r(53,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Time for Governor to return an ordinary bill for reconsideration (No limit)"),
 r(54,"History","Ancient",MCQ,"medium","specialized reference","Ruler of Assam in the time of Harsha (Bhaskar Varman)"),
 r(55,"History","Modern",MCQ,"hard","specialized reference","Who headed the Royal Commission on Indian currency 1913 (Austin Chamberlain)",ambiguous_subject="TRUE",ambiguous_note="could be Economy"),
 r(56,"Geography","World",MCQ,"easy","NCERT-level","Which city is on river Seine (Paris)"),
 r(57,"Current Affairs","Sports",MCQ,"medium","current_affairs","Aman Sehrawat's freestyle weight category for Paris 2024 (57 kg)",ca_recency_months=7),
 r(58,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Organisms with spore formation as reproduction (Fern)"),
 r(59,"History","Modern",MCQ,"hard","specialized reference","President of INC at Patna Session 1912 (R.N. Madhulkar)",ambiguous_subject="TRUE",ambiguous_note="Patna session — Bihar-linked"),
 r(60,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Direction-distance: Gaurav walks (60 metres)"),
 r(61,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","GVA sector shares FY2024 (Econ Survey 2023-24): Agri/Industry/Services"),
 r(62,"Geography","Economic",MCQ,"medium","NCERT-level","Corundum and cryolite are ores of (Aluminium)",ambiguous_subject="TRUE",ambiguous_note="ores — could be Sci & Tech/Chemistry"),
 r(63,"Geography","Human",MCQ,"easy","NCERT-level","Which is a technopolis (Silicon Valley)"),
 r(64,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Suitable condition for liquefaction of gases (low temp, high pressure)"),
 r(65,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Date National Flag adopted by Constituent Assembly (22 July 1947)"),
 r(66,"History","Modern",MCQ,"hard","specialized reference","Quit India parallel govts — which NOT correctly matched (Raiyati Sarkar-Kheda)"),
 r(67,"Current Affairs","National",MCQ,"medium","current_affairs","City named India's First UNESCO City of Literature, June 2024 (Kozhikode)",ca_recency_months=6),
 r(68,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Bihar centre under Vishnupad Yojana for tourism (Budget 2024) (Gaya)",ca_recency_months=5),
 r(69,"Current Affairs","Sports",MCQ,"medium","current_affairs","First Indian to scale Everest & Lhotse twice in one season (Satyadeep Gupta)",ca_recency_months=6),
 r(70,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Fluid part of the blood (Plasma)"),
 r(71,"Geography","Economic",MCQ,"medium","NCERT-level","Which port is an artificial port (Chennai)"),
 r(72,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Book 'Gharib Hindustan' banned in Bihar 1930 — author (Mohd. Wali Hassan)"),
 r(73,"Science & Technology","Chemistry",MCQ,"medium","specialized reference","First artificially prepared element (Technetium)"),
 r(74,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","When Bihar introduced Green Budget for the first time (FY 2020-21)"),
 r(75,"History","Medieval",MT,"medium","specialized reference","Match Ashta Pradhan (Maratha) officials with departments",list_item_count=4),
 r(76,"History","Modern",MCQ,"medium","specialized reference","Countries recognizing Bose's 1943 provisional govt (9)"),
 r(77,"History","Ancient",MCQ,"medium","specialized reference","Ruler who founded 'Haryak Vansh' in ancient Bihar (Bimbisara)",ambiguous_subject="TRUE",ambiguous_note="Magadha — Bihar-linked"),
 r(78,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Calendar: Feb 1 1996 Wed -> day on Mar 3 1996 (Saturday)"),
 r(79,"Geography","Economic",MCQ,"medium","NCERT-level","Which is a zaid crop"),
 r(80,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","Female LFPR increase 2017-18 to 2022-23 (NSSO) (23.3% to 37%)"),
 r(81,"History","Modern",MCQ,"medium","NCERT-level","Royal Titles Act — Queen Victoria became Empress of India (1876)"),
 r(82,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Melamine (floor tiles) is an example of (Thermosetting plastic)"),
 r(83,"Reasoning & Aptitude","Quantitative/Numerical",RA,"hard","specialized reference","Symbol-substitution arithmetic expression (0)"),
 r(84,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","'Hundred Years of INC in Bihar' edited by (P.N. Ojha)"),
 r(85,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Sex ratio in Bihar per Census 2011 (918)"),
 r(86,"Geography","World",MCQ,"easy","NCERT-level","The Andes extends along (West Coast of South America)"),
 r(87,"History","Medieval",MCQ,"hard","specialized reference","'Chach Nama' translated to Persian by (M.A. Bin Abu Bakr Kufi)"),
 r(88,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Radiation used for relief from body aches (Infra-red)"),
 r(89,"History","Ancient",MCQ,"medium","specialized reference","Dynasty that ruled Magadh after Shishunag (Nanda)",ambiguous_subject="TRUE",ambiguous_note="Magadha — Bihar-linked"),
 r(90,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Structural and functional unit of life (Cell)"),
 r(91,"Current Affairs","International",MCQ,"medium","current_affairs","Place where Trump was shot at a rally (Pennsylvania)",ca_recency_months=5),
 r(92,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Count triangles in figure PQRS (12)"),
 r(93,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Constituents of a soda-acid fire extinguisher"),
 r(94,"Geography","Human",MCQ,"easy","NCERT-level","Human race inhabiting China/Mongolia/Japan (Mongoloid)"),
 r(95,"History","Modern",MCQ,"medium","specialized reference","Which capitalist was NOT an architect of the Bombay Plan (Dhirubhai Ambani)"),
 r(96,"Bihar-Specific","Polity & Governance",MCQ,"hard","current_affairs","Community SC-listed by 2015 Bihar notification quashed Jul 2024 (Tanti-Tantwa)",ca_recency_months=5),
 r(97,"History","Modern",MCQ,"medium","NCERT-level","Economic foundation of India-China-England triangular trade (Opium)"),
 r(98,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Munger Hilly region — which physiographic region (Southern Hilly)"),
 r(99,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Code language: COMPUTER=RFUVQNPC -> MEDICINE"),
 r(100,"History","Medieval",MCQ,"hard","specialized reference","Malik Kafur ('Hazar Dinari') was bought by (Nusrat Khan)"),
 r(101,"History","Modern",MCQ,"medium","specialized reference","Struggle-Truce-Struggle strategy came into prominence with (Quit India)"),
 r(102,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Fertilizer component for stimulating early growth (Phosphorus)"),
 r(103,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","Year Bihar State Hydroelectric Power Corporation established (1992)"),
 r(104,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Manvi Madhu Kashyap became Bihar's first transgender ___",ca_recency_months=4),
 r(105,"Science & Technology","Biology",MCQ,"easy","NCERT-level","What chlorophyll is used for in photosynthesis (Absorbing light)"),
 r(106,"Current Affairs","Sports",MCQ,"medium","current_affairs","Author of 'I Have the Streets: A Kutti Cricket Story' (Ashwin & Monga)",ca_recency_months=4),
 r(107,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Goldman Environmental Prize 2024 winner from Asia (Alok Shukla)",ca_recency_months=8),
 r(108,"Bihar-Specific","History & Culture",MCQ,"easy","specialized reference","One-month cattle fair at Ganga-Gandak confluence (Sonepur Mela)"),
 r(109,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","14th term of sequence 14,10,6,2,... (-38)"),
 r(110,"Geography","Economic",MCQ,"easy","NCERT-level","Indian states with major coal reserves (All the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(111,"History","Ancient",MCQ,"medium","specialized reference","Capital of the Chera dynasty (Kuravur/Karur)"),
 r(112,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Which has a highly elongated elliptical orbit (Comet)"),
 r(113,"Polity","Constitutional provisions",MCQ,"medium","specialized reference","Which was NOT a feature of GoI Act 1935",ambiguous_subject="TRUE",ambiguous_note="could be Modern History"),
 r(114,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","Contribution of agriculture in Bihar's GDP (19%)"),
 r(115,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Who presented the Bihar Budget 2024-25 (Vijay Kumar Choudhary)",ca_recency_months=9),
 r(116,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Part of alimentary canal receiving bile from liver (Small intestine)"),
 r(117,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","RBI forecast for headline inflation FY2025 (5.0%)"),
 r(118,"Current Affairs","International",MCQ,"easy","current_affairs","Country that took over BRICS chairmanship Jan 1, 2024 (Russia)",ca_recency_months=11),
 r(119,"History","Modern",MT,"hard","specialized reference","Match newspaper with editor (Free Hindustan, Indian Opinion, Voice of India, Bengalee)",list_item_count=4),
 r(120,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","When the new province Bihar came into force under British rule (April 1912)"),
 r(121,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","How many times clock hands coincide in a day (22)"),
 r(122,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Which is a non-contact force (Magnetic force)"),
 r(123,"Current Affairs","International",MCQ,"medium","current_affairs","Where JIMEX-24 (Japan-India Maritime Exercise) was held (Vishakhapatnam)",ca_recency_months=6),
 r(124,"Economy","Banking & finance",MCQ,"medium","specialized reference","Full form of CGTMSE (Micro and Small Enterprises)"),
 r(125,"History","Ancient",ST,"hard","specialized reference","Ajivika sect statements — which correct",statement_count=4,option_combination_pattern="a, b and d"),
 r(126,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Which drainage system drains the lands of Bihar (Ghagra)"),
 r(127,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","Per Capita NSDP (current prices) for Bihar FY2022-23 (Rs 54,111)"),
 r(128,"Current Affairs","Awards & Appointments",MCQ,"easy","current_affairs","Payal Kapadia's Cannes Grand Prix 2024 film (All We Imagine as Light)",ca_recency_months=7),
 r(129,"Environment & Ecology","Climate & Pollution",MCQ,"easy","NCERT-level","Major cause of air pollution (provisional key: Disposal of plastics)"),
 r(130,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Figure/number pattern — value of ? (22)"),
 r(131,"History","Modern",MT,"hard","specialized reference","Match revolutionary org with HQ (Swadeshi Sevak Home, United India House, Yugantar Ashram, INA)",list_item_count=4),
 r(132,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Resistance of a wire formula (R=V/I)"),
 r(133,"Bihar-Specific","History & Culture",MCQ,"easy","specialized reference","Takht Sri Harimandir Ji Patna Sahib located at (Patna)"),
 r(134,"Current Affairs","Sports",MCQ,"medium","current_affairs","Theme of International Olympic Day 2024 (Together, For a Peaceful World)",ca_recency_months=6),
 r(135,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Union Textiles Minister after 18th Lok Sabha (provisional key: G.S. Shekhawat)",ca_recency_months=5),
 r(136,"Geography","Economic",MCQ,"medium","NCERT-level","Mineral in Minas Gerais province of Brazil (Iron ore)"),
 r(137,"Current Affairs","International",MCQ,"medium","current_affairs","Sheikh Ahmad al-Sabah appointed PM of which country Apr 2024 (Kuwait)",ca_recency_months=8),
 r(138,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","Sector with highest allocation in Bihar Budget 2024-25 (Education)"),
 r(139,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Amendment that abolished Anglo-Indian reserved seats (provisional key: 108th)"),
 r(140,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Value of the solar constant (1.4 kW/m2)"),
 r(141,"Economy","Banking & finance",MCQ,"hard","current_affairs","RBI criterion for SFB to become Universal Bank (provisional key: Rs 500 cr)"),
 r(142,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Breaking down organic matter by microorganisms (Decomposition)"),
 r(143,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","First Hindi daily newspaper published in Bihar (Kshatriya Samachar)"),
 r(144,"Current Affairs","International",MCQ,"medium","current_affairs","Where Ismail Haniyeh was assassinated 31 Jul 2024 (Iran)",ca_recency_months=5),
 r(145,"Geography","Economic",MCQ,"medium","current_affairs","Zoji-la Tunnel connects (Srinagar and Leh)"),
 r(146,"History","Ancient",ST,"hard","specialized reference","Land types per Amarkosha — which correct",statement_count=4,option_combination_pattern="More than one of the above"),
 r(147,"Current Affairs","Awards & Appointments",MCQ,"hard","current_affairs","Profession of Arti (Amal Clooney Women's Empowerment Award 2024) (ASHA worker)",ca_recency_months=7),
 r(148,"Economy","Five-year plans & policy",MCQ,"hard","current_affairs","NOT a Budget priority for 'Viksit Bharat' 2024-25 (Sustainable Development)",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(149,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Which is equivalent to tesla (Newton per ampere-metre)"),
 r(150,"Current Affairs","National",MCQ,"medium","current_affairs","Constituency of new Odisha CM Mohan Charan Majhi (provisional key: Laikera)",ca_recency_months=6),
]

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "70th.csv")
    n = write_rows(ROWS, out)
    print(f"wrote {n} rows -> {out}")
