"""67th BPSC Prelims RE-EXAM (30 Sep 2022), Series B, 5-option. Provisional key.
Tagged from English. correct_option auto-filled from official Series-B key (parsed from
the multi-series compact table — verified against known-answer questions).
Option E = 'None of the above/More than one of the above' on this paper.
"""
import os
from schema import COLUMNS, write_rows

KEY = {1:"B",2:"A",3:"A",4:"A",5:"D",6:"B",7:"D",8:"B",9:"C",10:"D",11:"D",12:"B",13:"A",14:"D",15:"A",
16:"D",17:"C",18:"D",19:"C",20:"D",21:"C",22:"D",23:"A",24:"D",25:"A",26:"A",27:"C",28:"A",29:"C",30:"D",
31:"B",32:"A",33:"D",34:"A",35:"B",36:"C",37:"B",38:"A",39:"B",40:"B",41:"D",42:"A",43:"D",44:"B",45:"B",
46:"B",47:"D",48:"D",49:"B",50:"A",51:"B",52:"B",53:"A",54:"D",55:"B",56:"D",57:"A",58:"B",59:"B",60:"D",
61:"B",62:"C",63:"A",64:"B",65:"A",66:"C",67:"D",68:"C",69:"B",70:"D",71:"B",72:"B",73:"C",74:"A",75:"B",
76:"B",77:"D",78:"C",79:"B",80:"B",81:"B",82:"C",83:"D",84:"D",85:"C",86:"B",87:"C",88:"D",89:"C",90:"C",
91:"D",92:"B",93:"C",94:"D",95:"C",96:"B",97:"C",98:"C",99:"D",100:"B",101:"C",102:"A",103:"B",104:"D",105:"C",
106:"D",107:"D",108:"C",109:"C",110:"D",111:"A",112:"A",113:"A",114:"C",115:"C",116:"D",117:"B",118:"A",119:"A",120:"C",
121:"B",122:"D",123:"C",124:"D",125:"D",126:"B",127:"E",128:"C",129:"A",130:"B",131:"A",132:"E",133:"E",134:"D",135:"E",
136:"B",137:"D",138:"D",139:"B",140:"E",141:"B",142:"C",143:"A",144:"B",145:"A",146:"C",147:"B",148:"B",149:"A",150:"A"}

DEF = dict(year="67th-reexam", exam_date="2022-09-30", paper_variant="re-exam", booklet_series="B",
           option_count=5, key_status="provisional", statement_count="", list_item_count="",
           option_combination_pattern="", is_all_or_none_correct="FALSE",
           all_none_literal_phrasing="FALSE", ambiguous_subject="FALSE", ambiguous_note="",
           ca_recency_months="")

def r(qn, subject, sub, qtype, diff, src, text, **kw):
    row = dict(DEF); row.update(kw)
    row.update(question_number=qn, subject=subject, sub_topic=sub, question_type=qtype,
               difficulty_guess=diff, source_type_guess=src, question_text_en=text,
               correct_option=KEY[qn])
    return row

ST, MT, MCQ, AR, RA = "statement_based", "match_the_following", "simple_mcq", "assertion_reason", "reasoning_aptitude"
ROWS = [
 r(1,"History","Modern",MCQ,"medium","NCERT-level","Who got Labour Dept portfolio in Interim Govt Cabinet 1946 (Jagjivan Ram)"),
 r(2,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","1942 festival when JP Narayan escaped Hazaribagh jail (Deepawali)"),
 r(3,"History","Modern",MCQ,"medium","NCERT-level","Dr. Rajendra Prasad elected Chairman of Constituent Assembly in (December 1946)",ambiguous_subject="TRUE",ambiguous_note="Rajendra Prasad — Bihar figure"),
 r(4,"History","Modern",MCQ,"easy","NCERT-level","Who is known as 'Frontier Gandhi' (Abdul Gaffar Khan)"),
 r(5,"History","Modern",MCQ,"easy","NCERT-level","Where did Rani Laxmibai of Jhansi die (Gwalior)"),
 r(6,"History","Modern",MCQ,"medium","specialized reference","Who said Bengal Partition 'fell like a bomb shell' (Surendra Nath Bannerjee)"),
 r(7,"History","Modern",MCQ,"medium","specialized reference","Sardar Udham Singh killed whom (Michael O'Dwyer)"),
 r(8,"History","Modern",MCQ,"medium","NCERT-level","Who successfully led the Bardoli Satyagraha (Vallabhbhai Patel)"),
 r(9,"History","Modern",MCQ,"medium","NCERT-level","Who was NOT a member of the 1946 Cabinet Mission (Ramsay MacDonald)"),
 r(10,"History","Modern",MCQ,"easy","NCERT-level","Year of the Gandhi-Irwin Pact (1931 AD)"),
 r(11,"History","Modern",MCQ,"medium","NCERT-level","Session where INC passed Complete Independence Resolution (1929 Lahore)"),
 r(12,"History","Modern",MCQ,"medium","specialized reference","Subhas Chandra Bose renamed Nicobar Island as (Swaraj Island)"),
 r(13,"History","Modern",MCQ,"easy","NCERT-level","State of 'Chauri Chaura' incident Feb 1922 (Uttar Pradesh)"),
 r(14,"Bihar-Specific","History & Culture",MCQ,"medium","NCERT-level","Place Khudiram Bose tried to kill Kingsford (Muzaffarpur)"),
 r(15,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","'Azad Dasta' active in Bihar during which Movement (Quit India)"),
 r(16,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Numbers 100-500 divisible by 4,5,6 (6)"),
 r(17,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Sand:cement ratio mixture problem (28 kg)"),
 r(18,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Oranges: 25% loss at Rs150/dozen, rate for 20% profit"),
 r(19,"Reasoning & Aptitude","Quantitative/Numerical",RA,"easy","specialized reference","Rhombus diagonals 10cm/24cm — perimeter (52 cm)"),
 r(20,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Train 140m at 60km/hr crosses dog at 18km/hr in (12 seconds)"),
 r(21,"Reasoning & Aptitude","Quantitative/Numerical",RA,"hard","specialized reference","Clock gains 10 min/24hr — right time when clock shows 11am next day"),
 r(22,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Clock hands coincide between 5 and 6"),
 r(23,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Anil+Suman work in 12 days, Anil alone 20 days — Suman alone (30 days)"),
 r(24,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Class 55: 34 like Cricket, 26 Badminton, both games — overlap (Venn diagram)"),
 r(25,"Reasoning & Aptitude","Quantitative/Numerical",RA,"hard","specialized reference","Two natural numbers: product 2400, sum of squares 5200 (60,40)"),
 r(26,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Plants receive nutrients mainly from (soil)"),
 r(27,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Pine/Fir/Spruce/Cedar/Larch/Cypress belong to (gymnosperm)"),
 r(28,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Correctly matched pair (disease-treatment)"),
 r(29,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Animal without red blood cells (earthworm)"),
 r(30,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Ultimate substance carbohydrates degraded to (glucose)"),
 r(31,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Most enzymes are (proteins)"),
 r(32,"Science & Technology","Biology",MCQ,"medium","NCERT-level","First scientist/doctor who attempted vaccination (Edward Jenner)"),
 r(33,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Working principle of a washing machine (centrifugation)"),
 r(34,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Speed of light minimum while passing through (glass)"),
 r(35,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Which is NOT a vector quantity (Speed)"),
 r(36,"Science & Technology","Physics",MCQ,"medium","NCERT-level","If earth's spinning speed increases, weight at equator will (decrease)"),
 r(37,"History","Ancient",MCQ,"hard","specialized reference","First person to define speed (Galileo)",ambiguous_subject="TRUE",ambiguous_note="could be Science & Tech/Physics"),
 r(38,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Equal volumes of gases contain equal molecules — law (Avogadro's law)"),
 r(39,"Science & Technology","Physics",MCQ,"easy","NCERT-level","'Theory of relativity' presented by (Albert Einstein)"),
 r(40,"Science & Technology","Physics",MCQ,"hard","NCERT-level","Potential variation due to temperature variation along conductor (Seebeck effect)"),
 r(41,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Lens used in magnifying glass (Convex lens)"),
 r(42,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Paramagnetic theory of magnetism applies to (platinum)"),
 r(43,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Nucleus of an atom consists of (protons and neutrons)"),
 r(44,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Metallurgical process where metal obtained in fused state (smelting)"),
 r(45,"Science & Technology","Chemistry",MCQ,"easy","NCERT-level","Constituents of brass (Zinc and copper)"),
 r(46,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Known as quicklime (CaO)"),
 r(47,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","What happens to weight of iron when it rusts (Increases for long time)"),
 r(48,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Known as white metal (Platinum)"),
 r(49,"Science & Technology","Chemistry",ST,"medium","NCERT-level","Noble metals statements — which correct",statement_count=2,option_combination_pattern="1 only"),
 r(50,"Science & Technology","Chemistry",ST,"medium","NCERT-level","Salt/methyl alcohol boiling point statements — which correct",statement_count=2,option_combination_pattern="1 only"),
 r(51,"Science & Technology","Chemistry",MCQ,"easy","NCERT-level","Main constituent of biogas (Methane)"),
 r(52,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Cause of bright red colour in crackers (Strontium)"),
 r(53,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Salt-loving plants called (Halophytes)"),
 r(54,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Fungi are plants that lack (chlorophyll)"),
 r(55,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Pollination best defined as (transfer of pollen grain anther to stigma)"),
 r(56,"Bihar-Specific","Polity & Governance",MT,"hard","current_affairs","Match Bihar posts with officeholders (Governor, CJ, CM, CEO)",list_item_count=4),
 r(57,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","'Operation Prahar' in Bihar related to (liquor ban)"),
 r(58,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Hrithik Anand from Bihar won which medal at 24th Deaf Badminton Olympics (Gold)"),
 r(59,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","North India's first bird ringing station opened in Bihar at (Bhagalpur)"),
 r(60,"Bihar-Specific","Recent Developments",MCQ,"medium","specialized reference","Which started the Vulture's Conservation Plan in Bihar (Kanwar Lake Bird Sanctuary)"),
 r(61,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","'Sunandini Program' related to (Auxiliary Nurse Midwives)"),
 r(62,"Current Affairs","International",MCQ,"easy","current_affairs","Country whose former PM Shinzo Abe was shot dead July 2022 (Japan)",ca_recency_months=3),
 r(63,"Current Affairs","International",MCQ,"medium","current_affairs","UN resolution on multilingualism — language mentioned for first time (Hindi)"),
 r(64,"Current Affairs","International",MCQ,"medium","current_affairs","Who presided UNGA emergency session on Russia-Ukraine (Abdulla Shahid)",ca_recency_months=7),
 r(65,"Current Affairs","International",MCQ,"medium","current_affairs","Mission to evacuate Indians from Ukraine Feb 2022 (Operation Ganga)",ca_recency_months=7),
 r(66,"Current Affairs","International",MCQ,"medium","current_affairs","'Sakteng Wildlife Sanctuary' China claims territory in (Bhutan)"),
 r(67,"Current Affairs","National",MCQ,"easy","current_affairs","Indian State/UT chosen to host G20 Summit 2023 (Delhi)"),
 r(68,"Current Affairs","International",ST,"medium","current_affairs","UN peacekeeping operations statements — which correct",statement_count=3,option_combination_pattern="1 and 2 only"),
 r(69,"Current Affairs","International",MCQ,"medium","current_affairs","Country signed FTA with UAE recently (Israel)",ambiguous_subject="TRUE",ambiguous_note="could be Economy/trade"),
 r(70,"Current Affairs","International",MCQ,"medium","current_affairs","Country launched 'Arktika-M' satellite to monitor Arctic climate (Russia)"),
 r(71,"Current Affairs","Sports",MCQ,"medium","current_affairs","First player to cross 3000 runs in T20 International (Virat Kohli)"),
 r(72,"Current Affairs","National",MCQ,"medium","current_affairs","Campaign for complete COVID-19 vaccination June 2022 (Har Ghar Dastak 2.0)",ca_recency_months=3),
 r(73,"Current Affairs","National",MCQ,"easy","current_affairs","New CM of Maharashtra after 30 June 2022 (Eknath Shinde)",ca_recency_months=3),
 r(74,"Current Affairs","National",MCQ,"easy","current_affairs","Who started Har Ghar Tiranga Abhiyan on India's 75th Independence Day (Central Government)",ca_recency_months=2),
 r(75,"Current Affairs","Schemes & Indices",MCQ,"medium","current_affairs","First State to implement Centre's New Education Policy (Uttarakhand)",ambiguous_subject="TRUE",ambiguous_note="could be Polity"),
 r(76,"Current Affairs","National",ST,"hard","current_affairs","Governor-State pairs — which correctly matched",statement_count=4,option_combination_pattern="1, 3 and 4 only"),
 r(77,"Current Affairs","Schemes & Indices",MCQ,"medium","current_affairs","Org released 'Youth in India Report 2022' (MoSPI)"),
 r(78,"Current Affairs","Sports",MCQ,"medium","current_affairs","Elavenil Valarivan, Shreya Agarwal, Ramita associated with (Shooting)"),
 r(79,"Current Affairs","Awards & Appointments",MCQ,"medium","current_affairs","Recently assigned charge of Ministry of Minority Affairs (Smriti Irani)"),
 r(80,"Current Affairs","National",MCQ,"easy","current_affairs","UPA candidate in 15th Presidential Election (Yashwant Sinha)",ca_recency_months=2),
 r(81,"Current Affairs","Awards & Appointments",MCQ,"easy","current_affairs","International Booker Prize for 'Tomb of Sand' (Geetanjali Shree)",ca_recency_months=4),
 r(82,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Dadasaheb Phalke Indian Television Award 2022 winner from Bihar (Shatrughan Sinha)"),
 r(83,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","Bihar urbanization level per Economic Survey 2021-22 (11.6%)"),
 r(84,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","Brand Ambassador of Khadi in Bihar (Manoj Tiwari)"),
 r(85,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","District where world's tallest (251m) Mother Sita statue will be built (Sitamarhi)"),
 r(86,"Bihar-Specific","Polity & Governance",MCQ,"hard","specialized reference","First Indian Governor of Bihar (Dr. Shri Krishna Singh)"),
 r(87,"Bihar-Specific","History & Culture",MCQ,"medium","NCERT-level","Leaders of the Santhal Revolt (Sidhu and Kanhu)"),
 r(88,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Year of the Chauri Revolt of Bihar (1842)"),
 r(89,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Year Orissa separated from Bihar (1936)"),
 r(90,"History","Ancient",MCQ,"medium","NCERT-level","Where was first Buddhist Council convened (Rajagriha)",ambiguous_subject="TRUE",ambiguous_note="Rajagriha — Bihar-linked"),
 r(91,"History","Ancient",MCQ,"medium","specialized reference","Which Gupta ruler assumed throne after killing elder brother (Chandragupta II)"),
 r(92,"History","Ancient",MCQ,"medium","specialized reference","Who laid foundation of Vardhana dynasty (Pushyabhuti)"),
 r(93,"History","Ancient",MCQ,"medium","NCERT-level","Who established trade relations with Roman empire (Kushanas)"),
 r(94,"History","Medieval",MCQ,"hard","specialized reference","Muslim ruler whose empire regarded part of Dar-ul-Islam (Iltutmish)"),
 r(95,"History","Medieval",MCQ,"medium","specialized reference","Who opposed the power of the Khalifa (Balban)"),
 r(96,"History","Medieval",MCQ,"medium","specialized reference","Tughril Khan raised standard of revolt during whose reign (Balban)"),
 r(97,"History","Modern",MCQ,"medium","NCERT-level","First Mughal ruler who fought against the British (Aurangzeb)"),
 r(98,"History","Modern",ST,"medium","NCERT-level","Social reforms introduced by William Bentinck",statement_count=4,option_combination_pattern="1, 3 and 4 only"),
 r(99,"History","Modern",MCQ,"medium","NCERT-level","Sind was conquered and annexed by (Napier)"),
 r(100,"History","Modern",MCQ,"medium","NCERT-level","Year first Census introduced in India (1872)"),
 r(101,"History","Modern",MCQ,"easy","NCERT-level","Date Sukhdev, Bhagat Singh, Rajguru were hanged (23 March 1931)"),
 r(102,"History","Modern",MCQ,"hard","specialized reference","Third Satyagrahi of Individual Satyagraha 1940 (Jawaharlal Nehru)"),
 r(103,"History","Modern",MCQ,"medium","specialized reference","Who launched secret radio during Quit India Movement (Usha Mehta)"),
 r(104,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Physician of Magadh ruler Bimbisara (Jeevaka)"),
 r(105,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Real founder of Turk rule in Bihar (Ibn Bakhtiyar Khilji)"),
 r(106,"Bihar-Specific","Geography",MCQ,"easy","specialized reference","River known as Sorrow of Bihar (Kosi)"),
 r(107,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","District where Telhar Kund Waterfall is located (Kaimur)"),
 r(108,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Asia's largest freshwater oxbow lake in Bihar (Kanwar Lake)"),
 r(109,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Bihar district with largest gold reserve (Jamui)"),
 r(110,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Bihar district known as 'silk city' (Bhagalpur)"),
 r(111,"Bihar-Specific","Geography",MCQ,"hard","specialized reference","Female literacy rate of Bihar per Census 2011 (51.50%)"),
 r(112,"Geography","Physical",MCQ,"easy","NCERT-level","Chief heavenly body of solar system (Sun)"),
 r(113,"Geography","Physical",MCQ,"medium","NCERT-level","Elements abundant in interior layer of earth (Silica and magnesium)"),
 r(114,"Geography","Physical",MCQ,"hard","specialized reference","Who postulated concept of geographical cycle of erosion (W.M. Davis)"),
 r(115,"Geography","World",MCQ,"medium","specialized reference","Hemisphere where roaring forties/furious fifties/shrieking sixties blow (Southern)"),
 r(116,"Geography","World",MCQ,"medium","specialized reference","Sargasso Sea is part of (North Atlantic Ocean)"),
 r(117,"Geography","Physical",MCQ,"easy","NCERT-level","Boundary line between India and China (McMahon Line)"),
 r(118,"Geography","Physical",MCQ,"medium","NCERT-level","Rajasthan receives very little rain because (winds don't come across barriers)"),
 r(119,"Environment & Ecology","Conservation & Policy",ST,"medium","current_affairs","Project Tiger / Biodiversity Day statements — which correct",statement_count=3,option_combination_pattern="1 and 3 only"),
 r(120,"Geography","Economic",MCQ,"medium","specialized reference","Karewas famous for which cultivation (Saffron)"),
 r(121,"Geography","Economic",MCQ,"medium","NCERT-level","Leading Indian producer of thorium (Kerala)"),
 r(122,"Geography","Economic",MCQ,"medium","specialized reference","Newsprint paper industry located at (Nepanagar)"),
 r(123,"Geography","Economic",MCQ,"medium","NCERT-level","Where was first coal mine in India mined (Raniganj)"),
 r(124,"Geography","Human",MCQ,"medium","NCERT-level","Largest Scheduled Tribe in India per Census 2011 (Bhil)"),
 r(125,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Total geographical area of Bihar State (94163 sq km)"),
 r(126,"Polity","Panchayati Raj & local governance",MCQ,"medium","NCERT-level","State Govt reviews financial position of Panchayats every 5 yrs via (finance commission)"),
 r(127,"Polity","Panchayati Raj & local governance",MCQ,"medium","NCERT-level","Objective of community development (Harmonious life)"),
 r(128,"Current Affairs","National",MCQ,"medium","current_affairs","Electoral College for 16th VP Election 2022 — number of members (788)",ca_recency_months=3),
 r(129,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","Indian President eligible for re-election how many times (Any number)"),
 r(130,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Generally how many sessions in Lok Sabha (3)"),
 r(131,"Polity","Constitutional provisions",MCQ,"hard","specialized reference","Chairman of First Law Commission in Independent India (M.C. Setalvad)"),
 r(132,"Polity","Constitutional provisions",MCQ,"hard","current_affairs","'One Nation One Election' would require amendment of which Article (Article 83)",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(133,"Polity","Panchayati Raj & local governance",MCQ,"medium","NCERT-level","Which State does NOT have Panchayat system (Nagaland)"),
 r(134,"Polity","Constitutional provisions",MCQ,"medium","current_affairs","Lok Sabha delimitation freezed till which year (2026)"),
 r(135,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","The Supreme Court is a (federal court)"),
 r(136,"Bihar-Specific","Geography",MCQ,"hard","specialized reference","Ascending order of Bihar districts by urbanization (Nalanda<Munger<Patna)"),
 r(137,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","Fiscal deficit expected as % of Bihar GSDP FY2022-23 (9.89%)"),
 r(138,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","NOT part of 'Saat Nischay Part-2 Scheme' of Bihar (Airways to everyone)"),
 r(139,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","Descending order of Bihar districts by per capita income"),
 r(140,"Economy","Macroeconomic concepts",MCQ,"hard","NCERT-level","Which statement NOT true about poverty estimates 68th round NSSO"),
 r(141,"Economy","Five-year plans & policy",MCQ,"medium","current_affairs","Which partly defines micro-enterprise in India (Investment not more than Rs 1 crore)"),
 r(142,"Current Affairs","Schemes & Indices",MCQ,"hard","current_affairs","Which is INCORRECT regarding Pradhan Mantri Krishi Sinchai Yojana (Construction of well)"),
 r(143,"Economy","Banking & finance",MCQ,"hard","specialized reference","Bhandari Committee is related to (regional rural banks' restructuring)"),
 r(144,"Economy","Banking & finance",MCQ,"medium","NCERT-level","Correct statement about National Pension Scheme (regulated by PFRDA)"),
 r(145,"Economy","Five-year plans & policy",MCQ,"medium","current_affairs","NOT included in priorities of India Budget 2022-23 (Disinvestment)"),
 r(146,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","Tax-GDP ratio in FY2021-22 in India (10.9%)"),
 r(147,"Economy","Macroeconomic concepts",MCQ,"hard","specialized reference","India's share in World Exports by commodity 2018 (1.7%)"),
 r(148,"Economy","Macroeconomic concepts",MCQ,"hard","current_affairs","Total wheat production India per 4th advance estimates 2020-21 (109.5 million tonnes)"),
 r(149,"Current Affairs","National",MCQ,"medium","current_affairs","Correct statement on the Vibrant Village Programme (border villages, northern border)"),
 r(150,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","INCORRECT statement per Economic Survey of Bihar 2021-22 (sector growth rates)"),
]

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "67th_re.csv")
    n = write_rows(ROWS, out)
    print(f"wrote {n} rows -> {out}")
