"""69th BPSC Prelims (30 Sep 2023), Series A, 4-option. Provisional key.
Tagged from English (official standard). correct_option auto-filled from official Series-A key.
Re-run to rebuild 69th.csv. Rows added batch-by-batch.
"""
import os
from schema import COLUMNS, write_rows

# Official Series-A answer key (parsed from 69th key PDF). 'Deleted' = BPSC dropped the question.
KEY = {1:"D",2:"A",3:"C",4:"C",5:"D",6:"D",7:"C",8:"C",9:"B",10:"C",11:"D",12:"C",13:"D",14:"A",15:"B",
16:"A",17:"D",18:"A",19:"D",20:"A",21:"C",22:"C",23:"C",24:"C",25:"A",26:"B",27:"B",28:"B",29:"D",30:"B",
31:"A",32:"B",33:"Deleted",34:"C",35:"A",36:"B",37:"D",38:"D",39:"C",40:"A",41:"D",42:"B",43:"C",44:"D",45:"C",
46:"A",47:"A",48:"A",49:"A",50:"A",51:"B",52:"C",53:"C",54:"C",55:"B",56:"C",57:"C",58:"B",59:"B",60:"B",
61:"C",62:"C",63:"C",64:"C",65:"B",66:"C",67:"C",68:"D",69:"A",70:"C",71:"A",72:"C",73:"C",74:"A",75:"D",
76:"D",77:"B",78:"A",79:"B",80:"A",81:"D",82:"D",83:"A",84:"A",85:"D",86:"A",87:"D",88:"C",89:"D",90:"C",
91:"A",92:"A",93:"A",94:"A",95:"B",96:"C",97:"C",98:"B",99:"C",100:"A",101:"D",102:"C",103:"D",104:"B",105:"C",
106:"A",107:"C",108:"B",109:"A",110:"C",111:"D",112:"D",113:"C",114:"D",115:"C",116:"A",117:"D",118:"B",119:"A",120:"D",
121:"D",122:"Deleted",123:"A",124:"C",125:"A",126:"C",127:"B",128:"C",129:"B",130:"D",131:"A",132:"B",133:"C",134:"B",135:"C",
136:"A",137:"C",138:"C",139:"B",140:"C",141:"C",142:"D",143:"B",144:"D",145:"B",146:"B",147:"D",148:"A",149:"C",150:"A"}

DEF = dict(year="69th", exam_date="2023-09-30", paper_variant="main", booklet_series="A",
           option_count=4, key_status="provisional", statement_count="", list_item_count="",
           option_combination_pattern="", is_all_or_none_correct="FALSE",
           all_none_literal_phrasing="FALSE", ambiguous_subject="FALSE", ambiguous_note="",
           ca_recency_months="")

def r(qn, subject, sub, qtype, diff, src, text, **kw):
    row = dict(DEF); row.update(kw)
    row.update(question_number=qn, subject=subject, sub_topic=sub, question_type=qtype,
               difficulty_guess=diff, source_type_guess=src, question_text_en=text,
               correct_option=KEY[qn])
    return row

ST, MT, MCQ = "statement_based", "match_the_following", "simple_mcq"
ROWS = [
 r(1,"Science & Technology","Tech & Innovation",ST,"medium","current_affairs","Which technologies enabled by 5G (IoT, Edge Computing, Network Slicing)",statement_count=3,option_combination_pattern="1, 2 and 3",is_all_or_none_correct="TRUE"),
 r(2,"Science & Technology","Tech & Innovation",MT,"hard","current_affairs","Match space missions with exploration (Cassini-Huygens, Juno, Artemis, VERITAS)",list_item_count=4),
 r(3,"Geography","Economic",MT,"medium","specialized reference","Match cloth with origin (Linen, Coir, Mohair, Down)",list_item_count=4,ambiguous_subject="TRUE",ambiguous_note="natural fibres — could be General Science/GK"),
 r(4,"Science & Technology","Biology",ST,"medium","specialized reference","Taeniasis / neurocysticercosis — statements correct",statement_count=2,option_combination_pattern="Both 1 and 2"),
 r(5,"Science & Technology","Tech & Innovation",ST,"medium","specialized reference","Which are computer languages (Cobra, Python, Squirrel, Java)",statement_count=4,option_combination_pattern="All of the above",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(6,"Science & Technology","Tech & Innovation",MCQ,"easy","current_affairs","Full form of GPT in ChatGPT",ca_recency_months=8),
 r(7,"Science & Technology","Biology",ST,"medium","NCERT-level","Which are NOT tastes of the tongue (7 items)",statement_count=7,option_combination_pattern="4 and 7"),
 r(8,"Science & Technology","Biology",ST,"medium","specialized reference","Correctly matched pairs (Anorexia, Insomnia, Dyspnoea, Anosmia)",statement_count=4,option_combination_pattern="Only 3 and 4"),
 r(9,"Science & Technology","Physics",MCQ,"medium","NCERT-level","What are pulsars"),
 r(10,"Science & Technology","Tech & Innovation",MCQ,"hard","current_affairs","Lab-grown diamonds — diamond seed used"),
 r(11,"Science & Technology","Tech & Innovation",MCQ,"easy","NCERT-level","Fibre used to make bulletproof jackets (Kevlar)"),
 r(12,"Science & Technology","Chemistry",ST,"hard","specialized reference","Full form(s) of HMX",statement_count=4,option_combination_pattern="Only 1"),
 r(13,"Science & Technology","Tech & Innovation",MCQ,"medium","current_affairs","Tesla humanoid robot launched Oct 2022 (Optimus)",ca_recency_months=11),
 r(14,"Science & Technology","Tech & Innovation",MCQ,"medium","specialized reference","What is the Manhattan Project",ambiguous_subject="TRUE",ambiguous_note="WWII history — could be History/Modern"),
 r(15,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Concave mirror image real/inverted/same-size — object position"),
 r(16,"Science & Technology","Physics",MCQ,"easy","NCERT-level","A photoelectric cell converts"),
 r(17,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Solute per unit volume/mass = ___ (concentration)"),
 r(18,"Science & Technology","Biology",MCQ,"medium","current_affairs","How do COVID vaccines stimulate an immune response"),
 r(19,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Which liquid is a bad conductor of electricity (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(20,"Science & Technology","Biology",MCQ,"easy","NCERT-level","DNA double helix discovered by (Watson & Crick)"),
 r(21,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Two masses free-falling near Moon's surface"),
 r(22,"Science & Technology","Biology",MCQ,"medium","specialized reference","How do vector vaccines work"),
 r(23,"Geography","Physical",MCQ,"medium","NCERT-level","Process that continually adds new crust (seafloor spreading)"),
 r(24,"Geography","Physical",MCQ,"easy","NCERT-level","Theory: crust pieces in constant slow motion (plate tectonics)"),
 r(25,"Science & Technology","Biology",MCQ,"easy","current_affairs","Expanded form of mRNA"),
 r(26,"Science & Technology","Physics",MCQ,"easy","NCERT-level","AC current can be produced by (dynamo)"),
 r(27,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Current density is scalar/vector"),
 r(28,"Science & Technology","Chemistry",MCQ,"hard","specialized reference","Basis of classification of medications"),
 r(29,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Which slows the reaction rate (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(30,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Input and output nerves meet at (CNS)"),
 r(31,"Current Affairs","National",MCQ,"medium","current_affairs","Shipwreck Tourism — Sunchi Reef/Amee Shoals/Grande Island location (Goa)",ambiguous_subject="TRUE",ambiguous_note="location — could be Geography"),
 r(32,"Current Affairs","International",ST,"medium","current_affairs","G20 members represent — which statistics correct",statement_count=3,option_combination_pattern="Only 1 and 3",ca_recency_months=1,ambiguous_subject="TRUE",ambiguous_note="could be Economy"),
 r(33,"Current Affairs","International",MCQ,"medium","current_affairs","Head of Russia's Wagner Mercenary Group",ca_recency_months=2),
 r(34,"Current Affairs","Schemes & Indices",MCQ,"medium","current_affairs","Global Gender Gap Report released by (WEF)"),
 r(35,"Current Affairs","International",MCQ,"medium","current_affairs","Queen Elizabeth II — correct statement",ca_recency_months=12),
 r(36,"Current Affairs","National",MCQ,"medium","current_affairs","Theme of DefExpo-2022 (Path to Pride)",ca_recency_months=11),
 r(37,"Current Affairs","International",MCQ,"medium","specialized reference","Thadingyut Festival celebrated in which country (Myanmar)",ambiguous_subject="TRUE",ambiguous_note="static GK/culture — could be Geography/World"),
 r(38,"Current Affairs","International",ST,"medium","specialized reference","White House statements — which correct",statement_count=4,option_combination_pattern="2, 3 and 4",ambiguous_subject="TRUE",ambiguous_note="static GK"),
 r(39,"Environment & Ecology","Conservation & Policy",MCQ,"medium","current_affairs","'Net Metering' seen in news in context of (solar billing)",ambiguous_subject="TRUE",ambiguous_note="could be Economy/S&T"),
 r(40,"Science & Technology","Physics",MT,"medium","NCERT-level","Match colour with combination (Magenta, Teal, Mauve, Cyan)",list_item_count=4),
 r(41,"Current Affairs","International",MCQ,"medium","current_affairs","Deep-sea submersible imploded near Titanic (Titan)",ca_recency_months=3),
 r(42,"Current Affairs","National",MT,"hard","specialized reference","Match footwear/fashion accessory with description (Beret, Stilettos, Aviators, Chignon, Brogue)",list_item_count=5,ambiguous_subject="TRUE",ambiguous_note="static general-knowledge (fashion) — no clean subject fit"),
 r(43,"Current Affairs","International",MCQ,"hard","current_affairs","Where former US President gave interview recently (Athens)"),
 r(44,"Current Affairs","Sports",ST,"medium","specialized reference","Sports pairs correctly matched (Flushing Meadows, Venus Rosewater Dish, Roland Garros, Australian Open)",statement_count=4,option_combination_pattern="2 and 4"),
 r(45,"Current Affairs","Schemes & Indices",MCQ,"hard","current_affairs","MHA Mother Tongue Survey (MTSI) Nov 2022 — number of languages (576)",ca_recency_months=10),
 r(46,"Environment & Ecology","Conservation & Policy",MCQ,"medium","current_affairs","State that launched SLCVC vulture-conservation committee (Tamil Nadu)",ambiguous_subject="TRUE",ambiguous_note="could be Current Affairs"),
 r(47,"Environment & Ecology","Biodiversity",MCQ,"hard","current_affairs","Asian Giant Tortoises released into which National Park (Ntangki)"),
 r(48,"Current Affairs","International",MCQ,"medium","current_affairs","Country that reaffirmed Arunachal as part of India (USA)"),
 r(49,"Current Affairs","Sports",MCQ,"medium","current_affairs","Rudrankksh Patil's medal at ISSF World C'ship Cairo (Gold)",ca_recency_months=12),
 r(50,"Current Affairs","Schemes & Indices",MCQ,"medium","specialized reference","NEP 2020 — vocational education integrated from which grade (Grade 6)",ambiguous_subject="TRUE",ambiguous_note="education policy — could be Polity"),
 r(51,"Current Affairs","International",MCQ,"medium","current_affairs","India signed ECTA with which country (Australia)",ca_recency_months=15,ambiguous_subject="TRUE",ambiguous_note="could be Economy/trade"),
 r(52,"Current Affairs","International",MCQ,"hard","current_affairs","Plain Language Act passed by which country (New Zealand)"),
 r(53,"Current Affairs","International",MCQ,"hard","current_affairs","Tillyardembiids (first plant pollinators) fossils discovered in (China)",ambiguous_subject="TRUE",ambiguous_note="could be Sci & Tech discovery"),
 r(54,"Environment & Ecology","Conservation & Policy",MCQ,"medium","current_affairs","'Lisbon Declaration' — conservation of what (Oceans)"),
 r(55,"History","Ancient",MCQ,"medium","NCERT-level","Animal NOT known to Indus Valley people (Horse)"),
 r(56,"History","Medieval",MCQ,"medium","NCERT-level","Which is NOT a UNESCO World Heritage Site (India Gate)",ambiguous_subject="TRUE",ambiguous_note="Art & Culture / static GK"),
 r(57,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","DPSP borrowed from Constitution of (Ireland)"),
 r(58,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Sikkim became a full-fledged State in (1975)",ambiguous_subject="TRUE",ambiguous_note="could be Modern History"),
 r(59,"Economy","Banking & finance",MCQ,"easy","NCERT-level","Which currency is the costliest (Pound Sterling)"),
 r(60,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Bihar Govt target year to be pollution-free by cutting carbon (2024)",ambiguous_subject="TRUE",ambiguous_note="Bihar + Environment"),
 r(61,"History","Ancient",MCQ,"easy","NCERT-level","Stupa/Chaitya/Vihara related to (Buddhism)"),
 r(62,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","'Sujini' in Bihar handicrafts (embroidery)"),
 r(63,"Bihar-Specific","History & Culture",ST,"hard","specialized reference","Vikramshila University statements — which INCORRECT",statement_count=4,option_combination_pattern="1 and 2",ambiguous_subject="TRUE",ambiguous_note="could be History/Ancient"),
 r(64,"History","Medieval",ST,"hard","NCERT-level","Babur's arrival led to — which correct (gunpowder, arch/dome, Timurid, cannons)",statement_count=4,option_combination_pattern="3 and 4"),
 r(65,"History","Medieval",MCQ,"medium","specialized reference","Port called Babul Makka in Mughal period (Surat)"),
 r(66,"History","Medieval",MCQ,"easy","NCERT-level","'Ashta Pradhan' Council of Ministers (Maratha)"),
 r(67,"History","Ancient",MCQ,"medium","NCERT-level","'Bodhisattva Padmapani' painting located at (Ajanta)"),
 r(68,"History","Ancient",ST,"medium","NCERT-level","Fa-Hien / Hiuen Tsang statements — which correct",statement_count=2,option_combination_pattern="None of the above",all_none_literal_phrasing="TRUE",is_all_or_none_correct="TRUE"),
 r(69,"History","Ancient",MT,"medium","NCERT-level","Match Charaka/Brahmagupta/Varahamihira/Vishakhadatta with field",list_item_count=4),
 r(70,"History","Medieval",MCQ,"medium","specialized reference","Who introduced Persian festival Nowruz in India (Balban)"),
 r(71,"History","Medieval",MCQ,"medium","NCERT-level","Nathpanthis/Siddhas/Yogis made devotional religion popular in (Northern India)"),
 r(72,"History","Modern",ST,"medium","NCERT-level","Wood's Dispatch 1854 statements — which correct",statement_count=2,option_combination_pattern="Both 1 and 2"),
 r(73,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Maithili language developed during which dynasty (Karnat)"),
 r(74,"History","Ancient",MCQ,"medium","NCERT-level","Capital of ancient Magadha in early Vedic period (Rajagriha)",ambiguous_subject="TRUE",ambiguous_note="Bihar (Magadha) history"),
 r(75,"History","Modern",ST,"medium","NCERT-level","Vernacular Press Act statements — which correct",statement_count=3,option_combination_pattern="1, 2 and 3",is_all_or_none_correct="TRUE"),
 r(76,"History","Modern",ST,"hard","specialized reference","Lord Mayo's Resolution 1870 statements — which correct",statement_count=4,option_combination_pattern="1, 2, 3 and 4",is_all_or_none_correct="TRUE"),
 r(77,"History","Ancient",MCQ,"hard","specialized reference","Nitisara (early book of politics) written by (Kamandaka)"),
 r(78,"History","Medieval",MCQ,"hard","specialized reference","Futuhat-i-Alamgiri written by (Ishwardas Nagar)"),
 r(79,"History","Ancient",MCQ,"hard","specialized reference","Meghavarman sent missionary to which Gupta king (Samudragupta)"),
 r(80,"Bihar-Specific","History & Culture",MCQ,"medium","NCERT-level","When Bihar first separated from Bengal Presidency (1912)",ambiguous_subject="TRUE",ambiguous_note="could be Modern History"),
 r(81,"Geography","World",ST,"hard","specialized reference","Lake Victoria statements — which INCORRECT",statement_count=4,option_combination_pattern="1 and 3"),
 r(82,"Geography","Physical",ST,"medium","NCERT-level","Heat wave criteria statements — which correct (Neither)",statement_count=2,option_combination_pattern="Neither 1 nor 2",is_all_or_none_correct="TRUE"),
 r(83,"Geography","World",MT,"hard","specialized reference","Match explorer with birthplace (Columbus, Cartier, Drake, Magellan)",list_item_count=4,ambiguous_subject="TRUE",ambiguous_note="explorers — could be History"),
 r(84,"Geography","World",MCQ,"medium","specialized reference","The emirates of UAE are"),
 r(85,"Geography","Physical",MCQ,"hard","specialized reference","Subarnarekha river originates near which village (Nagri)"),
 r(86,"Bihar-Specific","Geography",ST,"medium","specialized reference","Which National Parks/WLS are in Bihar (Valmiki, Bhimbandh)",statement_count=4,option_combination_pattern="1 and 4"),
 r(87,"Environment & Ecology","Biodiversity",ST,"medium","specialized reference","Gangetic Dolphin statements — which correct",statement_count=4,option_combination_pattern="1, 3 and 4"),
 r(88,"Geography","Physical",MCQ,"medium","NCERT-level","Other name of river Gandak (Narayani)",ambiguous_subject="TRUE",ambiguous_note="Bihar river"),
 r(89,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Gold found in which district of Bihar (Jamui)"),
 r(90,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Triveni Canal constructed on which river (Gandak)"),
 r(91,"Geography","Physical","assertion_reason","medium","NCERT-level","A-R: placer gold Ghana/Brazil; continents joined along Atlantic (continental drift)"),
 r(92,"Bihar-Specific","Geography",MT,"hard","specialized reference","Match Bihar rock systems with descriptions (Dharwar, Vindhyan, Quaternary, Tertiary)",list_item_count=4),
 r(93,"Environment & Ecology","Biodiversity",MCQ,"medium","specialized reference","World's richest marine biodiversity region — 21 islands (Gulf of Mannar)"),
 r(94,"Geography","Physical",MCQ,"medium","NCERT-level","Local time of Thimphu (90E) when Greenwich is noon",ambiguous_subject="TRUE",ambiguous_note="longitude time calculation — Reasoning element"),
 r(95,"Geography","Economic",MCQ,"medium","specialized reference","Which statement is correct (minerals: Mica in Kodarma)"),
 r(96,"Geography","Physical",MCQ,"medium","NCERT-level","How many latitudes at 1-degree interval on globe (179)"),
 r(97,"Bihar-Specific","Geography",MCQ,"hard","specialized reference","Average height of Kosi plain from MSL (30 m)"),
 r(98,"Geography","Physical",MCQ,"hard","specialized reference","On which plateau do Tropic of Cancer & IST line intersect (Baghelkhand)"),
 r(99,"Geography","Physical",MCQ,"hard","specialized reference","Which Uttarakhand district NOT along Tibet boundary (Almora)"),
 r(100,"Geography","Physical",MCQ,"medium","NCERT-level","Where does the El Nino current flow (Pacific Ocean)"),
 r(101,"Polity","Constitutional provisions",ST,"medium","NCERT-level","Collegium system statements — which correct",statement_count=4,option_combination_pattern="1 and 3"),
 r(102,"Polity","Constitutional provisions",ST,"medium","NCERT-level","42nd Amendment statements — which INCORRECT",statement_count=4,option_combination_pattern="2 and 3"),
 r(103,"Polity","Constitutional provisions",ST,"medium","NCERT-level","Specifications to declare a Scheduled Tribe — which correct",statement_count=4,option_combination_pattern="All of the above",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(104,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","Fundamental Rights idea taken from which country (USA)"),
 r(105,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","Untouchability abolished by which Article (17)"),
 r(106,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Authority to determine number of High Court Judges (Parliament)"),
 r(107,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Fifth Schedule deals with governance of (Scheduled Tribes)"),
 r(108,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Which case first gave 'basic structure' doctrine (Kesavananda Bharati)"),
 r(109,"Polity","Constitutional provisions",MT,"medium","specialized reference","Match political parties with year of establishment (CPI-M, CPI, BSP, AITC)",list_item_count=4,ambiguous_subject="TRUE",ambiguous_note="political-party GK"),
 r(110,"Polity","Constitutional provisions",MCQ,"hard","specialized reference","Article allowing Speaker to permit a member to speak in mother tongue"),
 r(111,"Economy","Banking & finance",ST,"medium","NCERT-level","RBI Forex Reserves include — which (FCA, Gold, SDR, RTP)",statement_count=4,option_combination_pattern="1, 2 and 3"),
 r(112,"Economy","Banking & finance",ST,"medium","specialized reference","'Rules of Origin' statements — which correct",statement_count=4,option_combination_pattern="All of the above",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(113,"Economy","Macroeconomic concepts",ST,"hard","specialized reference","Infant Mortality Rate statements — which correct",statement_count=4,option_combination_pattern="Only 2 and 3",ambiguous_subject="TRUE",ambiguous_note="demography — could be Current Affairs/health"),
 r(114,"Economy","Macroeconomic concepts",ST,"medium","NCERT-level","Human capital formation — what it enables",statement_count=4,option_combination_pattern="Only 4"),
 r(115,"Economy","Banking & finance",ST,"medium","specialized reference","Insolvency and bankruptcy statements — which correct",statement_count=4,option_combination_pattern="Only 4"),
 r(116,"Economy","Five-year plans & policy",MCQ,"medium","NCERT-level","In which year was the Industrial Policy Resolution adopted (1956)"),
 r(117,"Current Affairs","Schemes & Indices",ST,"hard","current_affairs","PLI scheme statements — which INCORRECT",statement_count=4,option_combination_pattern="2 and 3",ambiguous_subject="TRUE",ambiguous_note="scheme — could be Economy"),
 r(118,"Current Affairs","Schemes & Indices",ST,"hard","current_affairs","SVAMITVA scheme statements — which INCORRECT",statement_count=4,option_combination_pattern="1 and 3",ambiguous_subject="TRUE",ambiguous_note="scheme — could be Polity/Panchayati Raj"),
 r(119,"Polity","Constitutional provisions",ST,"hard","specialized reference","Consequences of invoking Article 360 (financial emergency)",statement_count=4,option_combination_pattern="Only 1, 3 and 4"),
 r(120,"Economy","Macroeconomic concepts",ST,"hard","specialized reference","Factors contributing to stagflation in Indian economy",statement_count=4,option_combination_pattern="1, 2, 3 and 4",is_all_or_none_correct="TRUE"),
 r(121,"Economy","Macroeconomic concepts",ST,"hard","current_affairs","Economic Survey 2023 — FDI trend statements",statement_count=4,option_combination_pattern="Only 4"),
 r(122,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","Current population of Gaya district of Bihar",ambiguous_subject="TRUE",ambiguous_note="demography"),
 r(123,"Economy","Macroeconomic concepts",MCQ,"medium","NCERT-level","Non-plan expenditure of Central Govt — which correct (interest payments)"),
 r(124,"Economy","Macroeconomic concepts",MCQ,"medium","NCERT-level","Which is NOT true about globalization & its impact on India"),
 r(125,"Economy","Macroeconomic concepts",ST,"hard","current_affairs","Union Govt finances statements (fiscal deficit FY21/FY22)",statement_count=3,option_combination_pattern="Only 1"),
 r(126,"History","Modern",ST,"medium","NCERT-level","Reasons for failure of the Revolt of 1857",statement_count=3,option_combination_pattern="All of the above",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(127,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Cook from Bihar who saved Gandhi's life in 1917 (Batak Mian)"),
 r(128,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Bakasht Movement in Bihar 1937-38 organized by (Sahajanand Saraswati)"),
 r(129,"History","Modern",ST,"hard","NCERT-level","Chronological order: Home Rule, Surat Split, Kheda Satyagraha, Minto-Morley",statement_count=4,option_combination_pattern="2-4-1-3"),
 r(130,"History","Modern",MCQ,"medium","specialized reference","Lord Lytton NOT associated with which (Ilbert Bill)"),
 r(131,"History","Modern",MCQ,"medium","NCERT-level","Treaty signed after the Battle of Buxar (Allahabad)"),
 r(132,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Dutch East India Company factory at Patna in which year (1632)"),
 r(133,"History","Modern",MCQ,"medium","NCERT-level","Gandhi's first use of hunger strike as a weapon (Ahmedabad Strike)"),
 r(134,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Bihar leader known as 'Bihar Kesari' in Quit India (Shri Krishna Singh)"),
 r(135,"History","Modern",MCQ,"medium","NCERT-level","British response to Champaran Movement (Agrarian Committee)",ambiguous_subject="TRUE",ambiguous_note="Champaran — Bihar-linked"),
 r(136,"History","Modern",MT,"medium","specialized reference","Match reform societies with founders (Servants of India, Tattwabodhini, Atmiya Sabha)",list_item_count=3),
 r(137,"History","Modern",MCQ,"hard","specialized reference","Ambabai, woman freedom fighter, from which State (Karnataka)"),
 r(138,"History","Modern",MCQ,"medium","NCERT-level","Who was NOT a member of the Cabinet Mission (J. Andrew)"),
 r(139,"History","Modern",MCQ,"medium","specialized reference","'INC founded on safety-valve theory' — which leader said (Lala Lajpat Rai)"),
 r(140,"History","Modern",MCQ,"medium","specialized reference","INC session where Fundamental Rights resolutions first passed (Karachi 1931)"),
 r(141,"Reasoning & Aptitude","Logical/Verbal","reasoning_aptitude","medium","specialized reference","Code language: GAME/BEAD -> MADE"),
 r(142,"Reasoning & Aptitude","Logical/Verbal","reasoning_aptitude","medium","specialized reference","Direction reasoning (Q, M, S, T travel directions)"),
 r(143,"Reasoning & Aptitude","Quantitative/Numerical","reasoning_aptitude","medium","specialized reference","Land plot percentage math (Ramesh vs Suresh)"),
 r(144,"Reasoning & Aptitude","Logical/Verbal","reasoning_aptitude","medium","specialized reference","Find the odd pair (Millinery, Brewery, Stationery, Snobbery)"),
 r(145,"Reasoning & Aptitude","Quantitative/Numerical","reasoning_aptitude","medium","specialized reference","Number series: 132 156 ? 210 240 272"),
 r(146,"Reasoning & Aptitude","Quantitative/Numerical","reasoning_aptitude","medium","specialized reference","Missing number in 3x3 matrix (44,49,37 / 52,?,41 / 58,35,53)"),
 r(147,"Reasoning & Aptitude","Logical/Verbal","reasoning_aptitude","medium","specialized reference","Statement-conclusion: cricket runs by spinners"),
 r(148,"Reasoning & Aptitude","Logical/Verbal","reasoning_aptitude","hard","specialized reference","Code language: GREAT/MONK -> VIGOROUS"),
 r(149,"Reasoning & Aptitude","Logical/Verbal","reasoning_aptitude","medium","specialized reference","Find the odd one in letter groups"),
 r(150,"Reasoning & Aptitude","Quantitative/Numerical","reasoning_aptitude","hard","specialized reference","Direction-distance: company branches M,N,O,P"),
]

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "69th.csv")
    n = write_rows(ROWS, out)
    print(f"wrote {n} rows -> {out}")
