"""68th BPSC Prelims (12 Feb 2023), Series A, 5-option. FINAL key.
Tagged from English. correct_option auto-filled from official Series-A FINAL key.
Option E = 'None of the above' / 'More than one of the above' on this paper.
"""
import os
from schema import COLUMNS, write_rows

KEY = {1:"A",2:"C",3:"C",4:"B",5:"D",6:"D",7:"A",8:"E",9:"C",10:"A",11:"A",12:"D",13:"B",14:"A",15:"E",
16:"A",17:"B",18:"E",19:"A",20:"C",21:"A",22:"Deleted",23:"A",24:"C",25:"D",26:"B",27:"B",28:"B",29:"C",30:"B",
31:"D",32:"C",33:"C",34:"B",35:"C",36:"A",37:"E",38:"B",39:"A",40:"A",41:"E",42:"E",43:"B",44:"A",45:"B",
46:"C",47:"A",48:"C",49:"C",50:"C",51:"B",52:"B",53:"C",54:"B",55:"A",56:"A",57:"A",58:"C",59:"C",60:"B",
61:"B",62:"C",63:"B",64:"E",65:"B",66:"A",67:"A",68:"C",69:"C",70:"B",71:"C",72:"B",73:"C",74:"C",75:"A",
76:"A",77:"C",78:"B",79:"C",80:"A",81:"C",82:"A",83:"C",84:"B",85:"C",86:"E",87:"E",88:"C",89:"B",90:"A",
91:"D",92:"D",93:"C",94:"E",95:"B",96:"C",97:"A",98:"B",99:"B",100:"A",101:"D",102:"C",103:"C",104:"A",105:"E",
106:"C",107:"B",108:"C",109:"D",110:"A",111:"C",112:"B",113:"C",114:"C",115:"C",116:"B",117:"A",118:"C",119:"B",120:"C",
121:"B",122:"A",123:"A",124:"A",125:"B",126:"B",127:"B",128:"C",129:"A",130:"E",131:"B",132:"C",133:"A",134:"A",135:"B",
136:"B",137:"B",138:"A",139:"B",140:"C",141:"C",142:"C",143:"B",144:"B",145:"A",146:"C",147:"B",148:"B",149:"C",150:"A"}

DEF = dict(year="68th", exam_date="2023-02-12", paper_variant="main", booklet_series="A",
           option_count=5, key_status="final", statement_count="", list_item_count="",
           option_combination_pattern="", is_all_or_none_correct="FALSE",
           all_none_literal_phrasing="FALSE", ambiguous_subject="FALSE", ambiguous_note="",
           ca_recency_months="")

def r(qn, subject, sub, qtype, diff, src, text, **kw):
    row = dict(DEF); row.update(kw)
    row.update(question_number=qn, subject=subject, sub_topic=sub, question_type=qtype,
               difficulty_guess=diff, source_type_guess=src, question_text_en=text,
               correct_option=KEY[qn])
    return row

ST, MT, MCQ, AR, RA = "statement_based", "match_the_following", "simple_mcq", "assertion_reason", "reasoning_aptitude"
ROWS = [
 r(1,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","'Equality before law' Art 14 borrowed from Constitution of (Britain)"),
 r(2,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","Duration of making the Indian Constitution (2yr 11mo 18days)"),
 r(3,"Polity","Constitutional provisions",MCQ,"easy","NCERT-level","State Council of Ministers collectively responsible to (Legislative Assembly)"),
 r(4,"Polity","Panchayati Raj & local governance",ST,"medium","NCERT-level","Post-73rd Amendment decentralization — which statements correct",statement_count=4,option_combination_pattern="1, 2 and 4 only"),
 r(5,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Representation in Rajya Sabha includes (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(6,"Polity","Constitutional provisions",MCQ,"medium","NCERT-level","Concerned with the Supreme Court of India (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(7,"Polity","Panchayati Raj & local governance",MCQ,"easy","NCERT-level","Min age to contest Panchayati Raj elections per 73rd CAA (21 years)"),
 r(8,"Economy","Banking & finance",MCQ,"hard","specialized reference","District Consumer Disputes Redressal — which statement is NOT correct (None of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(9,"Polity","Panchayati Raj & local governance",MCQ,"easy","NCERT-level","At what level does Panchayat Samiti operate (Block-level body)"),
 r(10,"Economy","Five-year plans & policy",MCQ,"medium","NCERT-level","First programme of community development (National Extension Service)"),
 r(11,"Economy","Five-year plans & policy",ST,"medium","current_affairs","Objectives of the SEZ Act 2005",statement_count=3,option_combination_pattern="1, 2 and 3",is_all_or_none_correct="TRUE"),
 r(12,"Economy","Macroeconomic concepts",MCQ,"medium","NCERT-level","Policy measure to improve agricultural marketing (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(13,"Economy","Banking & finance",MCQ,"hard","specialized reference","Committee that suggested Competition Act 2002 (S.V.S. Raghavan Committee)"),
 r(14,"Economy","Five-year plans & policy",MT,"hard","specialized reference","Match Revolution with produce (Grey, Pink, Silver, Red)",list_item_count=4),
 r(15,"Economy","Five-year plans & policy",MCQ,"medium","NCERT-level","Five-Year Plan focused on Human Resource Development (Fifth)"),
 r(16,"Current Affairs","National",MCQ,"medium","current_affairs","State with highest FDI equity flow Apr-Sep 2022 (Gujarat)",ca_recency_months=5,ambiguous_subject="TRUE",ambiguous_note="could be Economy"),
 r(17,"Economy","Banking & finance",MCQ,"hard","NCERT-level","Budget that announced Liberalized Exchange Rate Management System (1992-93)"),
 r(18,"Economy","Five-year plans & policy",ST,"medium","NCERT-level","Goals of the Five-Year Plans",statement_count=4,option_combination_pattern="1, 2 and 4 only"),
 r(19,"Economy","Macroeconomic concepts",MCQ,"medium","NCERT-level","Org that surveys for determining poverty line (NSSO)"),
 r(20,"Current Affairs","National",MCQ,"hard","current_affairs","India's trade balance Dec 2022 provisional (- 11.98 USD bn)",ca_recency_months=2,ambiguous_subject="TRUE",ambiguous_note="could be Economy"),
 r(21,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","Bihar's lowest Female Workforce Participation Rate 2020-22 (7% rural, 9.1% urban)"),
 r(22,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","Bihar district with maximum tax industries (Darbhanga)"),
 r(23,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","NFHS-5: Bihar sex ratio improvement 2015-16 to 2020-22 (1040 to 1070)"),
 r(24,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","Bihar Economic Survey 2021-22 — GSDP growth rate 2020-21 (2%)"),
 r(25,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","Which is correct for Bihar economy (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(26,"History","Modern",MCQ,"medium","NCERT-level","Swadeshi and Boycott adopted first during (Partition of Bengal)"),
 r(27,"History","Modern",MCQ,"medium","specialized reference","Flag of Swaraj unfurled at 1906 Calcutta Session by (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(28,"History","Modern",MCQ,"medium","NCERT-level","Parallel movement in Indian States during freedom struggle (State People's Movement)"),
 r(29,"History","Modern",MCQ,"medium","NCERT-level","Which statement about freedom struggle NOT correct (Gandhi's first speech at BHU)"),
 r(30,"History","Modern",MCQ,"medium","specialized reference","Journal brought out by Abul Kalam Azad (Al-Hilal)"),
 r(31,"History","Modern",MCQ,"medium","NCERT-level","How study of history created nationalism feeling (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(32,"History","Modern",ST,"medium","NCERT-level","Non-Cooperation Movement in towns — which NOT correct",statement_count=3,option_combination_pattern="2 and 3 only"),
 r(33,"History","Modern",MCQ,"hard","specialized reference","Peasant leader — sanyasi with Tulsidas Ramayana (Yadunandan Sharma)",ambiguous_subject="TRUE",ambiguous_note="could be Bihar-Specific"),
 r(34,"History","Modern",MCQ,"medium","NCERT-level","Founder of All India Harijan Sangh 1932 (Mahatma Gandhi)"),
 r(35,"History","Modern",MCQ,"medium","NCERT-level","Attlee's Feb 20 1947 announcement — British withdrawal latest by (June 1948)"),
 r(36,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Who established Swaraj Dal in Bihar (Ramlal Shah)"),
 r(37,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Salt Satyagraha in Bihar — tax opposed alongside salt (Development)"),
 r(38,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Shri Krishna Singh govt resigned Feb 1938 for (Satyagraha against British at Gandhi's call)"),
 r(39,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Who saved Gandhiji's life in Bihar during Champaran Satyagraha (Batak Mian)"),
 r(40,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Who led cultivators in Bihar during Non-Cooperation Movement (Raj Kumar Shukla)"),
 r(41,"History","Ancient",MCQ,"medium","specialized reference","Area south of Ganga in ancient times known as (Anarta)"),
 r(42,"History","Ancient",MCQ,"medium","NCERT-level","When did use of iron begin in Indian subcontinent (Around 6000 years ago)"),
 r(43,"History","Ancient",MCQ,"hard","specialized reference","Sudarshan Lake reservoir repaired by (Rudradaman)"),
 r(44,"History","Ancient",MCQ,"medium","specialized reference","Deogarh temple + Garhwa sculptures are remains of (Gupta art)"),
 r(45,"History","Medieval",MCQ,"medium","NCERT-level","Which battle has opponents NOT correctly stated (Second Panipat - Tipu Sultan/Marathas)"),
 r(46,"History","Medieval",MCQ,"medium","specialized reference","'Muqaddam/Chaudhari' in Delhi Sultanate used for (village headman)"),
 r(47,"History","Medieval",MCQ,"hard","specialized reference","'Tabaqat-i-Akbari' (more reliable than Akbarnama) written by (Nizamuddin Ahmad)"),
 r(48,"History","Medieval",MCQ,"hard","specialized reference","Ruler who founded Nagalapuram township after mother's name (Krishnadevaraya)"),
 r(49,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Patna Women's College 1940 founded by which society (Sisters of Apostolic Carmel)"),
 r(50,"History","Modern",MCQ,"medium","specialized reference","Who headed the two 1947 India-Pakistan Boundary Commissions (Cyril Radcliffe)"),
 r(51,"History","Modern",MCQ,"medium","specialized reference","Who introduced Mahalwari Settlement in Bengal (Holt Mackenzie)"),
 r(52,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","1940 Vinoba Bhave started individual Satyagraha from (Pavnar, Maharashtra)",ambiguous_subject="TRUE",ambiguous_note="could be plain History/Modern"),
 r(53,"History","Modern",MCQ,"medium","specialized reference","Congress Montford Reforms 1918 split — moderates formed (Indian National Liberal Federation)"),
 r(54,"History","Modern",ST,"medium","NCERT-level","Cabinet Mission sent to India for",statement_count=3,option_combination_pattern="2 only"),
 r(55,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Who offered Humayun to surrender Bihar for annual tribute (Sher Khan)"),
 r(56,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Vikramshila University established by (Dharmapala)"),
 r(57,"Bihar-Specific","Polity & Governance",MCQ,"medium","specialized reference","First Governor of Bihar (Sir James David Sifton)"),
 r(58,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","Author of 'Mahatma Gandhi and Bihar, Some Reminiscences' (Dr. Rajendra Prasad)"),
 r(59,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Oldest church in Bihar (Padri Ki Haveli)"),
 r(60,"Bihar-Specific","History & Culture",MCQ,"medium","specialized reference","Kumudlal Ganguly (Ashok Kumar) born in which Bihar city (Bhagalpur)"),
 r(61,"Current Affairs","Schemes & Indices",MCQ,"medium","current_affairs","Union Ministry that launched YUVA 2.0 Scheme 2022 (Education)",ca_recency_months=3),
 r(62,"Current Affairs","National",MCQ,"medium","current_affairs","MHA Mother Tongue Survey Nov 2022 — number of languages (576)",ca_recency_months=3),
 r(63,"Current Affairs","National",MCQ,"medium","current_affairs","Committee that submitted report on gas pricing (Kirit Parikh Committee)",ca_recency_months=1,ambiguous_subject="TRUE",ambiguous_note="could be Economy"),
 r(64,"Current Affairs","National",MCQ,"medium","current_affairs","City NOT conferred 5-star garbage-free rank, Swachh Survekshan 2022 (Bhopal)",ca_recency_months=2),
 r(65,"Current Affairs","National",MCQ,"medium","current_affairs","PM inaugurated first greenfield 'Donyi Polo Airport' at (Itanagar)",ca_recency_months=1),
 r(66,"Current Affairs","National",MCQ,"medium","current_affairs","Animal approved as food animal by FSSAI Nov 2022 (Himalayan yak)",ca_recency_months=3),
 r(67,"Current Affairs","National",MCQ,"medium","current_affairs","India's first floating financial literacy camp by IPPB in (Andaman Islands)"),
 r(68,"Current Affairs","National",MCQ,"medium","current_affairs","President inaugurated 'PARAM KAMRUPA' Supercomputer at which IIT (Guwahati)"),
 r(69,"Current Affairs","National",MCQ,"easy","current_affairs","90th IAF Day air display 8 Oct 2022 held over (Dal Lake, J&K)",ca_recency_months=4),
 r(70,"Current Affairs","Schemes & Indices",MCQ,"easy","current_affairs","Month celebrated as Rashtriya Poshan Maah (September)"),
 r(71,"Current Affairs","International",MCQ,"medium","current_affairs","Final module of China's Tiangong Space Station recently launched (Mengtian)",ca_recency_months=4),
 r(72,"Environment & Ecology","Climate & Pollution",MCQ,"medium","current_affairs","World's largest volcano erupted first time in 38 years (Mauna Loa)",ca_recency_months=3),
 r(73,"Current Affairs","Awards & Appointments",MCQ,"easy","current_affairs","2022 Booker Prize winner for 'The Seven Moons of Maali Almeida' (Shehan Karunatilaka)",ca_recency_months=4),
 r(74,"Current Affairs","International",MCQ,"medium","current_affairs","Theme of World Space Week 2022 (Space and Sustainability)",ca_recency_months=4),
 r(75,"Science & Technology","Physics",MCQ,"medium","current_affairs","Lab that claimed nuclear fusion breakthrough Dec 2022 (Lawrence Livermore)",ca_recency_months=2),
 r(76,"Current Affairs","International",MCQ,"medium","current_affairs","Collins Dictionary word of the year 2022 (Permacrisis)",ca_recency_months=3),
 r(77,"Current Affairs","International",MCQ,"medium","current_affairs","Country with Senegal launched Intl Drought Resilience Alliance COP27 (Germany)",ca_recency_months=3),
 r(78,"Current Affairs","International",MCQ,"medium","current_affairs","Embassy that first applied for GI Tag for 'Nihonshu' in India (Japan)"),
 r(79,"Science & Technology","Tech & Innovation",MCQ,"medium","current_affairs","Space agency that used steam to propel EQUULEUS spacecraft (JAXA)"),
 r(80,"Current Affairs","Sports",MCQ,"medium","current_affairs","Tesla humanoid robot launched Oct 2022 (Optimus)",ca_recency_months=4),
 r(81,"Bihar-Specific","Recent Developments",MCQ,"hard","current_affairs","First floating solar power plant built at which place in Bihar (Kadirabad, Darbhanga)"),
 r(82,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","Economic Survey 2019-20 — Bihar district with lowest per capita income (Sheohar)"),
 r(83,"Bihar-Specific","Economy",MCQ,"hard","specialized reference","NITI Aayog SDG Report 2020-21 — Bihar's score (52 out of 100)"),
 r(84,"Current Affairs","Sports",MCQ,"medium","current_affairs","Sport included in Khelo India Women's Tournament for first time (Track Cycling)",ca_recency_months=3),
 r(85,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","GI Tag awarded August 2022 (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(86,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Added to UNESCO World Heritage List 2022 (Archaeological Site of Nalanda Mahavihara)"),
 r(87,"Bihar-Specific","Economy",MCQ,"hard","current_affairs","Bihar 2020 rank in Ease of Doing Business BRAP (24th)"),
 r(88,"Bihar-Specific","Recent Developments",MCQ,"medium","current_affairs","Ganga Jal Aapurti Yojana inaugurated by CM Nov 28 2022 at (Rajgir)",ca_recency_months=3),
 r(89,"Current Affairs","Sports",MCQ,"medium","current_affairs","Board declared equal pay for men/women players Oct 2022 (BCCI)",ca_recency_months=4),
 r(90,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","Bihar urbanization level 2011 census to present (11.3, 15.3)"),
 r(91,"Geography","Physical",MCQ,"medium","NCERT-level","Indus River joined at Attock by which river from Afghanistan (Kabul River)"),
 r(92,"Environment & Ecology","Conservation & Policy",MCQ,"easy","NCERT-level","Well-publicised wildlife campaign launched 1973 (Project Tiger)"),
 r(93,"Geography","Physical",MCQ,"medium","NCERT-level","Which statement true about troposphere (avg height 13 km)"),
 r(94,"Geography","Physical",MCQ,"medium","NCERT-level","Southern continent broken from Pangaea (Gondwanaland)"),
 r(95,"Geography","Physical",MCQ,"easy","NCERT-level","Arctic and Antarctica situated near (North and South Poles)"),
 r(96,"Geography","Physical",MCQ,"medium","NCERT-level","States with common border with Myanmar (Arunachal, Nagaland, Manipur, Mizoram)"),
 r(97,"Environment & Ecology","Biodiversity",MCQ,"medium","specialized reference","World's richest marine biodiversity region — 21 islands (Gulf of Mannar)"),
 r(98,"Geography","Physical",MCQ,"hard","specialized reference","UP and Bihar's Koppen climatic classification (Aw)",ambiguous_subject="TRUE",ambiguous_note="Bihar-linked"),
 r(99,"Geography","Physical",MCQ,"medium","NCERT-level","India's territorial limit into sea (12 nautical miles)"),
 r(100,"Geography","Economic",MCQ,"easy","NCERT-level","River valley rich in coal reserves (Damodar River Valley)"),
 r(101,"Geography","Economic",MCQ,"medium","NCERT-level","Which statement true about sugar industry in India (UP 2nd largest producer)"),
 r(102,"Geography","Physical",MCQ,"medium","NCERT-level","Pre-monsoon showers in Kerala/coastal Karnataka known as (Mango showers)"),
 r(103,"Geography","Physical",MCQ,"medium","NCERT-level","Atmosphere mainly heated by (long-wave terrestrial radiation)"),
 r(104,"Bihar-Specific","Geography",MCQ,"medium","specialized reference","State bordering max districts in Bihar (Uttar Pradesh)"),
 r(105,"Bihar-Specific","Geography",MCQ,"hard","specialized reference","Last railway station of Bihar towards Mirza Cheuki (Kahalgaon)"),
 r(106,"Bihar-Specific","Geography",ST,"hard","specialized reference","Mineral production in Bihar — which statements correct",statement_count=3,option_combination_pattern="1 and 2 only"),
 r(107,"Bihar-Specific","Geography",MCQ,"hard","specialized reference","Phalgu river formed by confluence of (Lilajan and Mohana rivers)"),
 r(108,"Bihar-Specific","History & Culture",MCQ,"hard","specialized reference","First tea gardens established in Bihar at (Thakurganj)"),
 r(109,"Bihar-Specific","Geography",MCQ,"hard","specialized reference","Ascending decadal population growth 2001-2011 order (Kishanganj<Madhepura<Siwan)"),
 r(110,"Bihar-Specific","Economy",MCQ,"medium","specialized reference","Dominant food industry among agro-based industries in Bihar (Cereal-based)"),
 r(111,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Convex lens image of white horse with black paint strips (horse of black stripes)"),
 r(112,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Shrillness of sound determined by (wavelength/frequency of sound)"),
 r(113,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Photoelectric device most suitable for digital applications (Photodiode)"),
 r(114,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Ball bearings convert static friction into (rolling friction)"),
 r(115,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Goalkeeper pulling hands back enables (decrease rate of change of momentum)"),
 r(116,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Positively charged particle emitted by radioactive element (Alpha ray)"),
 r(117,"Science & Technology","Physics",MCQ,"easy","NCERT-level","Centripetal force is responsible to (keep body moving along circular path)"),
 r(118,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Energy change involving frictional force (Kinetic to heat energy)"),
 r(119,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Bus sharp right turn — passengers will (bent towards right side)"),
 r(120,"Science & Technology","Physics",MCQ,"medium","NCERT-level","Sitarist adjusting string tension before orchestra adjusts (frequency matching)"),
 r(121,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Matter with no fixed shape but fixed volume (kerosene)"),
 r(122,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Examples of amphoteric oxides (Al2O3 and ZnO)"),
 r(123,"Environment & Ecology","Climate & Pollution",MCQ,"easy","NCERT-level","Gas that contributes to global warming via greenhouse effect (More than one)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(124,"Science & Technology","Chemistry",MCQ,"easy","NCERT-level","Acids react with metal carbonates to liberate ___ gas (CO2)"),
 r(125,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Acid described as HOOCCOOH (Oxalic acid)"),
 r(126,"Science & Technology","Chemistry",MCQ,"easy","NCERT-level","Turns red litmus to blue (Base)"),
 r(127,"Science & Technology","Chemistry",MCQ,"easy","NCERT-level","Odour of acetic acid resembles (vinegar)"),
 r(128,"Science & Technology","Chemistry",MCQ,"hard","NCERT-level","Why dry HCl gas doesn't change dry litmus colour (no H3O+ ions present)"),
 r(129,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Detect the odd one (Ripening of fruit)"),
 r(130,"Science & Technology","Chemistry",MCQ,"medium","NCERT-level","Which statement about diamond/graphite true (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
 r(131,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Stomata open/close due to change in (amount of water in cells)"),
 r(132,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Chlorophyll absorbs ___ wavelengths of sunlight (red and blue)"),
 r(133,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Which is NOT a correct match (plant stem types)"),
 r(134,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Water reaches great heights in trees due to suction pull caused by (transpiration)"),
 r(135,"Science & Technology","Biology",MCQ,"hard","NCERT-level","Chloroplast character enabling self-replication (Presence of both DNA and RNA)"),
 r(136,"Science & Technology","Biology",MCQ,"easy","NCERT-level","Skeleton parts not as hard as bones, can bend (cartilage)"),
 r(137,"Science & Technology","Biology",MCQ,"medium","NCERT-level","In lichen, chlorophyll-containing partner ___ live together (alga and a fungus)"),
 r(138,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Female Anopheles distinguished from Culex by sitting (at angle with substratum)"),
 r(139,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Cell type most important for body immunity (lymphocytes)"),
 r(140,"Science & Technology","Biology",MCQ,"medium","NCERT-level","Which statement INCORRECT about muscles (can only push the bone)"),
 r(141,"Reasoning & Aptitude","Logical/Verbal",RA,"hard","specialized reference","Code language: FASTER/MONK -> GUIDE"),
 r(142,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Rectangle area 30cm2 perimeter 26cm — sides (10, 3)"),
 r(143,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","10% discount + 10% GST on Rs 400 item — final price (Rs 396)"),
 r(144,"Reasoning & Aptitude","Logical/Verbal",RA,"medium","specialized reference","Arrange words in logical order (VP, President, Speaker, PM, MPs)"),
 r(145,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Reshma donates 1/4 property, divides rest among 3 children — each gets (one-fourth)"),
 r(146,"Reasoning & Aptitude","Logical/Verbal",RA,"easy","NCERT-level","Which statement is false (geometry: square/rhombus/rectangle)"),
 r(147,"Reasoning & Aptitude","Logical/Verbal",RA,"hard","specialized reference","Family relation puzzle: how is K related to S (Sister-in-law)"),
 r(148,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","How many words (meaningless) from letters of 'DIARY' (10)"),
 r(149,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Missing number in 3x3 matrix (44,49,37/52,?,41/58,35,53)"),
 r(150,"Reasoning & Aptitude","Quantitative/Numerical",RA,"medium","specialized reference","Missing number in series 15,20,32,62,118,248,? (More than one of the above)",is_all_or_none_correct="TRUE",all_none_literal_phrasing="TRUE"),
]

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "68th.csv")
    n = write_rows(ROWS, out)
    print(f"wrote {n} rows -> {out}")
