update public.questions set body = 'Read the following passage and answer the item that follows. Your answer should be based solely on the passage.

Passage
The public library is one of the few places in an Indian town where a person can sit for hours without being asked to buy anything. That, more than its books, may be its real value today. A student whose family of five shares a single room needs a quiet table more than a new title; a retired clerk needs company as much as newspapers. Libraries that judge themselves by the number of books issued miss what their busiest users come for, and those that close at five in the evening shut their doors just when working people are free. A library that stayed open late, with good light, clean toilets and reliable internet, might be the cheapest public investment a town could make in its young people.

Which one of the following best sums up the passage?', body_hi = 'निम्नलिखित परिच्छेद को पढ़िए और उसके बाद दिए गए प्रश्नांश का उत्तर दीजिए। आपका उत्तर केवल परिच्छेद पर आधारित होना चाहिए।

परिच्छेद
सार्वजनिक पुस्तकालय किसी भारतीय कस्बे की उन गिनी-चुनी जगहों में से है जहाँ कोई व्यक्ति कुछ ख़रीदने को कहे बिना घंटों बैठ सकता है। आज उसकी असली क़ीमत शायद उसकी पुस्तकों से अधिक यही है। जिस विद्यार्थी का पाँच लोगों का परिवार एक ही कमरे में रहता है, उसे नई पुस्तक से अधिक एक शांत मेज़ की ज़रूरत है; किसी सेवानिवृत्त क्लर्क को अख़बारों जितनी ही संगत की ज़रूरत है। जो पुस्तकालय स्वयं को जारी की गई पुस्तकों की संख्या से आँकते हैं, वे यह नहीं समझ पाते कि उनके सबसे नियमित उपयोगकर्ता किस लिए आते हैं, और जो शाम पाँच बजे बंद हो जाते हैं, वे ठीक तभी दरवाज़े बंद कर देते हैं जब कामकाजी लोग ख़ाली होते हैं। देर तक खुला रहने वाला पुस्तकालय, अच्छी रोशनी, साफ़ शौचालयों और भरोसेमंद इंटरनेट के साथ, शायद वह सबसे सस्ता सार्वजनिक निवेश हो जो कोई कस्बा अपने युवाओं में कर सकता है।

निम्नलिखित में से कौन-सा कथन परिच्छेद का सबसे अच्छा सारांश है?', question_data = '{"craft": "inference", "csat_set": "csat-l2-t01", "passage_group": "csat-l2-t01-p04", "csat_order": 27}'::jsonb, options = '[{"id": "a", "body": "Libraries should spend more of their money on new books and newspapers.", "body_hi": "पुस्तकालयों को अपना अधिक धन नई पुस्तकों और अख़बारों पर ख़र्च करना चाहिए।", "isCorrect": false}, {"id": "b", "body": "Working people have no time at all to use the public libraries in their towns.", "body_hi": "कामकाजी लोगों के पास अपने कस्बों के सार्वजनिक पुस्तकालयों का उपयोग करने का बिल्कुल भी समय नहीं है।", "isCorrect": false}, {"id": "c", "body": "Libraries matter as public spaces and should be run around their users'' needs.", "body_hi": "पुस्तकालय सार्वजनिक स्थान के रूप में अहम हैं, और उन्हें पाठकों की ज़रूरतों के अनुसार चलना चाहिए।", "isCorrect": true}, {"id": "d", "body": "The internet has now made the public library quite unnecessary for most young people.", "body_hi": "इंटरनेट ने अब अधिकांश युवाओं के लिए सार्वजनिक पुस्तकालय को बिल्कुल अनावश्यक बना दिया है।", "isCorrect": false}]'::jsonb, explanation = 'The passage argues that a library''s value today lies in its space -- a quiet table, company, long hours -- and that it should be run around what its users need. Spending more on books is the measure the passage questions; ''working people have no time'' misreads the point that libraries close just when such people are free; the internet appears in the passage as something a library should offer, not as its replacement.', explanation_hi = 'परिच्छेद का तर्क है कि आज पुस्तकालय की क़ीमत उसकी जगह में है -- एक शांत मेज़, संगत, देर तक खुले रहना -- और उसे उपयोगकर्ताओं की ज़रूरतों के अनुसार चलाया जाना चाहिए। पुस्तकों पर अधिक ख़र्च वही पैमाना है जिस पर परिच्छेद प्रश्न उठाता है; ''कामकाजी लोगों के पास समय नहीं'' इस बात को ग़लत पढ़ता है कि पुस्तकालय ठीक तभी बंद होते हैं जब ऐसे लोग ख़ाली होते हैं; इंटरनेट परिच्छेद में ऐसी चीज़ के रूप में आता है जो पुस्तकालय को देनी चाहिए, उसके विकल्प के रूप में नहीं।' where concept_group_id = 'csat-l2-t01-rc-p04-summary' and status = 'draft' returning concept_group_id;
update public.questions set body = 'Read the following passage and answer the item that follows. Your answer should be based solely on the passage.

Passage
Fact-checkers can correct a false story only after it has spread, and by then the correction reaches a fraction of the people who saw the original. Research on misinformation points to another approach: teaching people, before they meet a falsehood, the tricks that make it persuasive -- the doctored photograph, the fake expert, the appeal to outrage. People who have seen these tricks explained are better at spotting them later, much as a vaccine prepares the body for a virus it has not yet met. The method has limits. It works better against techniques than against particular claims, and its effect fades unless it is refreshed. But it does not depend on anyone deciding what is true, which makes it harder to dismiss as censorship.

Which one of the following statements best reflects the crux of the passage?', body_hi = 'निम्नलिखित परिच्छेद को पढ़िए और उसके बाद दिए गए प्रश्नांश का उत्तर दीजिए। आपका उत्तर केवल परिच्छेद पर आधारित होना चाहिए।

परिच्छेद
तथ्य-जाँचकर्ता किसी झूठी ख़बर को उसके फैल जाने के बाद ही सुधार सकते हैं, और तब तक सुधार उन लोगों के एक छोटे भाग तक ही पहुँचता है जिन्होंने मूल ख़बर देखी थी। ग़लत सूचना पर हुए शोध एक दूसरे तरीके की ओर इशारा करते हैं: लोगों को किसी झूठ से सामना होने से पहले ही वे तरकीबें सिखाना जो उसे विश्वसनीय बनाती हैं -- छेड़छाड़ की गई तस्वीर, नकली विशेषज्ञ, आक्रोश भड़काने वाली अपील। जिन लोगों को ये तरकीबें समझाई गई हैं, वे बाद में इन्हें बेहतर पहचान पाते हैं, ठीक वैसे ही जैसे टीका शरीर को किसी ऐसे वायरस के लिए तैयार करता है जिससे उसका अभी सामना नहीं हुआ। इस तरीके की सीमाएँ हैं। यह किसी विशेष दावे के बजाय तरकीबों के विरुद्ध बेहतर काम करता है, और दोहराया न जाए तो इसका असर घटता जाता है। पर यह इस पर निर्भर नहीं कि कोई यह तय करे कि सच क्या है, इसलिए इसे सेंसरशिप कहकर ख़ारिज करना कठिन है।

निम्नलिखित में से कौन-सा कथन परिच्छेद के सार को सबसे अच्छी तरह व्यक्त करता है?', question_data = '{"craft": "inference", "csat_set": "csat-l2-t01", "passage_group": "csat-l2-t01-p06", "csat_order": 39}'::jsonb, options = '[{"id": "a", "body": "Fact-checking should be given up, because its corrections always arrive far too late.", "body_hi": "तथ्य-जाँच को छोड़ देना चाहिए, क्योंकि उसके सुधार हमेशा बहुत ही देर से पहुँचते हैं।", "isCorrect": false}, {"id": "b", "body": "Most misinformation spreads through photographs that have been doctored.", "body_hi": "अधिकांश ग़लत सूचना छेड़छाड़ की गई तस्वीरों से फैलती है।", "isCorrect": false}, {"id": "c", "body": "Teaching people to spot persuasion tricks can beat correcting each falsehood later.", "body_hi": "बहकाने की तरकीबें पहचानना सिखाना, हर झूठ को बाद में सुधारने से बेहतर हो सकता है।", "isCorrect": true}, {"id": "d", "body": "Governments should decide which stories are true and remove all the others.", "body_hi": "सरकारों को यह तय करना चाहिए कि कौन-सी ख़बरें सच हैं, और बाक़ी सभी ख़बरें हटा देनी चाहिए।", "isCorrect": false}]'::jsonb, explanation = 'The passage sets correction after the fact against preparing people in advance, and argues for the second despite its limits. The first distractor overreaches: the passage notes the limits of fact-checking but never says it should be given up. The second turns one example, the doctored photograph, into a general claim. The third is the opposite of the passage, which values the method because it does not depend on anyone deciding what is true.', explanation_hi = 'परिच्छेद बाद में किए जाने वाले सुधार की तुलना पहले से तैयार करने से करता है, और सीमाओं के बावजूद दूसरे के पक्ष में तर्क देता है। पहला ग़लत विकल्प बहुत आगे जाता है: परिच्छेद तथ्य-जाँच की सीमाएँ बताता है, पर कहीं नहीं कहता कि उसे छोड़ देना चाहिए। दूसरा एक उदाहरण, छेड़छाड़ की गई तस्वीर, को सामान्य दावा बना देता है। तीसरा परिच्छेद के उलट है, जो इस तरीके को इसलिए महत्त्व देता है कि यह किसी के सच तय करने पर निर्भर नहीं।' where concept_group_id = 'csat-l2-t01-rc-p06-crux' and status = 'draft' returning concept_group_id;
update public.questions set body = 'Read the following passage and answer the item that follows. Your answer should be based solely on the passage.

Passage
For two decades India measured progress in schooling by enrolment, and by that measure it succeeded: almost every child of primary-school age is now on a school''s rolls. Surveys that test children directly tell a less cheerful story. Large numbers of children in the upper primary classes cannot read a text meant for a much younger class, or do a simple division. The trouble is not that these children never learnt; it is that the curriculum moved on before they did, and teachers, bound to finish the syllabus, taught to the front rows. Programmes that group children by what they can actually do, rather than by their age, and teach from that level, have raised reading scores quickly and cheaply. The difficulty is that such teaching looks, to an inspector with a syllabus in hand, like falling behind.

Which one of the following statements best reflects the crux of the passage?', body_hi = 'निम्नलिखित परिच्छेद को पढ़िए और उसके बाद दिए गए प्रश्नांश का उत्तर दीजिए। आपका उत्तर केवल परिच्छेद पर आधारित होना चाहिए।

परिच्छेद
दो दशकों तक भारत ने स्कूली शिक्षा में प्रगति को नामांकन से मापा, और उस पैमाने पर वह सफल रहा: प्राथमिक विद्यालय की आयु का लगभग हर बच्चा अब किसी विद्यालय के रजिस्टर में है। बच्चों की सीधे परीक्षा लेने वाले सर्वेक्षण कम उत्साहजनक तस्वीर दिखाते हैं। उच्च प्राथमिक कक्षाओं के बहुत-से बच्चे अपने से कहीं छोटी कक्षा के लिए लिखा गया पाठ नहीं पढ़ पाते, या एक साधारण भाग नहीं कर पाते। समस्या यह नहीं कि इन बच्चों ने कभी सीखा ही नहीं; समस्या यह है कि पाठ्यक्रम उनसे पहले आगे बढ़ गया, और पाठ्यक्रम पूरा करने के लिए बँधे शिक्षकों ने आगे की पंक्तियों को ही पढ़ाया। जो कार्यक्रम बच्चों को उनकी आयु के बजाय वे वास्तव में जो कर सकते हैं उसके अनुसार समूहों में बाँटते हैं, और उसी स्तर से पढ़ाते हैं, उन्होंने पढ़ने के अंक जल्दी और कम ख़र्च में बढ़ाए हैं। कठिनाई यह है कि हाथ में पाठ्यक्रम लिए किसी निरीक्षक को ऐसा शिक्षण पिछड़ने जैसा दिखता है।

निम्नलिखित में से कौन-सा कथन परिच्छेद के सार को सबसे अच्छी तरह व्यक्त करता है?', question_data = '{"craft": "inference", "csat_set": "csat-l2-t01", "passage_group": "csat-l2-t01-p09", "csat_order": 61}'::jsonb, options = '[{"id": "a", "body": "India has not yet managed to bring most of its children into school.", "body_hi": "भारत अभी तक अपने अधिकांश बच्चों को विद्यालय तक नहीं ला पाया है।", "isCorrect": false}, {"id": "b", "body": "Most of India''s teachers have never been properly trained to teach children to read.", "body_hi": "भारत के अधिकांश शिक्षकों को बच्चों को पढ़ना सिखाने का ठीक से प्रशिक्षण कभी नहीं मिला।", "isCorrect": false}, {"id": "c", "body": "Teaching must start from what children can do, not from their class syllabus.", "body_hi": "पढ़ाई कक्षा के पाठ्यक्रम से नहीं, बच्चे जो कर सकते हैं वहाँ से शुरू होनी चाहिए।", "isCorrect": true}, {"id": "d", "body": "School inspectors should stop visiting schools to check on their teachers.", "body_hi": "विद्यालय निरीक्षकों को शिक्षकों की जाँच के लिए विद्यालय जाना बंद कर देना चाहिए।", "isCorrect": false}]'::jsonb, explanation = 'The passage moves from enrolment to learning, finds the cause in a curriculum that ''moved on before they did'', and praises teaching from the level children have reached. The first distractor contradicts the passage, which says enrolment succeeded; the second names a cause the passage does not give; the third draws a conclusion about inspectors that the passage does not draw.', explanation_hi = 'परिच्छेद नामांकन से सीखने की ओर बढ़ता है, कारण उस पाठ्यक्रम में पाता है जो ''उनसे पहले आगे बढ़ गया'', और बच्चों के पहुँचे हुए स्तर से पढ़ाने की प्रशंसा करता है। पहला ग़लत विकल्प परिच्छेद का खंडन करता है, जो कहता है कि नामांकन सफल रहा; दूसरा ऐसा कारण बताता है जो परिच्छेद नहीं देता; तीसरा निरीक्षकों के बारे में ऐसा निष्कर्ष निकालता है जो परिच्छेद नहीं निकालता।' where concept_group_id = 'csat-l2-t01-rc-p09-crux' and status = 'draft' returning concept_group_id;
update public.questions set body = 'Read the following passage and answer the item that follows. Your answer should be based solely on the passage.

Passage
Public trust in science is often discussed as though it were a fixed stock that experts either keep or squander. It behaves more like the trust people place in a doctor. People trust a doctor who explains what she knows and what she does not, who changes her advice when the evidence changes, and who does not pretend that a hard trade-off is a purely technical question. Scientists who, in a crisis, present every recommendation as certain may win obedience in the short run, but each later revision then looks like a broken promise. Admitting uncertainty feels risky to an expert facing an anxious public; in the long run, hiding it is riskier.

Which one of the following statements best reflects the crux of the passage?', body_hi = 'निम्नलिखित परिच्छेद को पढ़िए और उसके बाद दिए गए प्रश्नांश का उत्तर दीजिए। आपका उत्तर केवल परिच्छेद पर आधारित होना चाहिए।

परिच्छेद
विज्ञान में जनता के भरोसे की चर्चा प्रायः ऐसे की जाती है मानो वह कोई निश्चित भंडार हो जिसे विशेषज्ञ या तो बचाए रखते हैं या गँवा देते हैं। वह अधिकतर उस भरोसे की तरह व्यवहार करता है जो लोग किसी डॉक्टर पर करते हैं। लोग उस डॉक्टर पर भरोसा करते हैं जो बताती है कि वह क्या जानती है और क्या नहीं, जो प्रमाण बदलने पर अपनी सलाह बदलती है, और जो किसी कठिन संतुलन को पूरी तरह तकनीकी प्रश्न होने का दिखावा नहीं करती। जो वैज्ञानिक संकट के समय हर सिफ़ारिश को निश्चित बताकर पेश करते हैं, वे थोड़े समय के लिए आज्ञापालन पा सकते हैं, पर बाद में होने वाला हर संशोधन तब टूटे वादे जैसा लगता है। चिंतित जनता के सामने अनिश्चितता स्वीकार करना किसी विशेषज्ञ को जोखिम भरा लगता है; लंबे समय में उसे छिपाना अधिक जोखिम भरा है।

निम्नलिखित में से कौन-सा कथन परिच्छेद के सार को सबसे अच्छी तरह व्यक्त करता है?', question_data = '{"craft": "inference", "csat_set": "csat-l2-t01", "passage_group": "csat-l2-t01-p10", "csat_order": 69}'::jsonb, options = '[{"id": "a", "body": "Scientists should avoid giving any advice at all in a time of crisis.", "body_hi": "वैज्ञानिकों को संकट के समय कोई भी सलाह देने से बचना चाहिए।", "isCorrect": false}, {"id": "b", "body": "Experts keep public trust by being open about what they do not know.", "body_hi": "विशेषज्ञ अपनी अनजानी बातें खुलकर बताकर जनता का भरोसा बनाए रखते हैं।", "isCorrect": true}, {"id": "c", "body": "People trust their doctors far more than they trust scientists.", "body_hi": "लोग वैज्ञानिकों की तुलना में अपने डॉक्टरों पर कहीं अधिक भरोसा करते हैं।", "isCorrect": false}, {"id": "d", "body": "Once lost, public trust in science can never be won back again.", "body_hi": "एक बार खोया हुआ विज्ञान पर जनता का भरोसा फिर कभी नहीं लौटता।", "isCorrect": false}]'::jsonb, explanation = 'The passage argues that trust is kept by candour -- saying what is not known and revising openly -- and that projecting certainty backfires when advice changes. Avoiding advice in a crisis is not suggested; the comparison with doctors is an analogy, not a ranking of whom people trust more; and the passage rejects the view of trust as a fixed stock that, once lost, can never be won back.', explanation_hi = 'परिच्छेद का तर्क है कि भरोसा स्पष्टता से बना रहता है -- यह बताना कि क्या ज्ञात नहीं और खुलकर संशोधन करना -- और यह कि सलाह बदलने पर निश्चितता का दिखावा उलटा पड़ता है। संकट में सलाह न देने का सुझाव नहीं दिया गया; डॉक्टरों से तुलना एक उपमा है, यह क्रम नहीं कि लोग किस पर अधिक भरोसा करते हैं; और परिच्छेद भरोसे को ऐसा निश्चित भंडार मानने वाले दृष्टिकोण को नकारता है जो एक बार खो जाने पर कभी वापस नहीं मिलता।' where concept_group_id = 'csat-l2-t01-rc-p10-crux' and status = 'draft' returning concept_group_id;
