update public.questions set body = 'Read the following passage and answer the item that follows. Your answer should be based solely on the passage.

Passage
Cities are warmer than the countryside around them, and the gap is widest on still summer nights. Concrete and asphalt soak up heat through the day and give it back after dark, while the cooling that trees provide -- by shading the ground and by evaporating water from their leaves -- is missing. The poorest neighbourhoods, with the least green cover and the most tin roofs, often run several degrees hotter than leafy ones a few kilometres away. Planting trees is the obvious remedy, but a sapling planted today will not shade a street for a decade, and many plantation drives count the saplings planted rather than the trees that survive. Cool roofs painted in reflective white, and shaded bus stops, can lower temperatures within a single season. A heat plan that relies on trees alone is a plan for the next decade, not for the next summer.

Which one of the following statements best reflects the crux of the passage?', body_hi = 'निम्नलिखित परिच्छेद को पढ़िए और उसके बाद दिए गए प्रश्नांश का उत्तर दीजिए। आपका उत्तर केवल परिच्छेद पर आधारित होना चाहिए।

परिच्छेद
शहर अपने आसपास के ग्रामीण क्षेत्रों से अधिक गर्म होते हैं, और यह अंतर गर्मियों की शांत रातों में सबसे अधिक होता है। कंक्रीट और डामर दिन भर गर्मी सोखते हैं और अँधेरा होने पर उसे लौटाते हैं, जबकि पेड़ों से मिलने वाली ठंडक -- ज़मीन पर छाया करके और पत्तियों से पानी का वाष्पन करके -- वहाँ नहीं होती। सबसे ग़रीब बस्तियाँ, जहाँ हरियाली सबसे कम और टिन की छतें सबसे अधिक हैं, प्रायः कुछ किलोमीटर दूर की हरी-भरी बस्तियों से कई डिग्री अधिक गर्म रहती हैं। पेड़ लगाना स्पष्ट उपाय है, पर आज लगाया गया पौधा एक दशक तक किसी सड़क को छाया नहीं देगा, और कई वृक्षारोपण अभियान बचे हुए पेड़ों के बजाय लगाए गए पौधों की गिनती करते हैं। चमकदार सफ़ेद रंग से रँगी ठंडी छतें और छायादार बस-स्टॉप एक ही मौसम में तापमान घटा सकते हैं। केवल पेड़ों पर टिकी गर्मी-योजना अगले दशक की योजना है, अगली गर्मी की नहीं।

निम्नलिखित में से कौन-सा कथन परिच्छेद के सार को सबसे अच्छी तरह व्यक्त करता है?', question_data = '{"craft": "inference", "csat_set": "csat-l2-t01", "passage_group": "csat-l2-t01-p01", "csat_order": 6}'::jsonb, options = '[{"id": "a", "body": "Planting trees does little to reduce heat in cities.", "body_hi": "पेड़ लगाने से शहरों की गर्मी बहुत कम घटती है।", "isCorrect": false}, {"id": "b", "body": "Poor neighbourhoods are hotter than others mainly because of their tin roofs.", "body_hi": "ग़रीब बस्तियाँ मुख्यतः अपनी टिन की छतों के कारण दूसरी बस्तियों से अधिक गर्म हैं।", "isCorrect": false}, {"id": "c", "body": "Plantation drives should count surviving trees, not saplings planted.", "body_hi": "वृक्षारोपण अभियानों को लगाए गए पौधों के बजाय बचे हुए पेड़ गिनने चाहिए।", "isCorrect": false}, {"id": "d", "body": "Tree planting must be paired with measures that cool cities quickly.", "body_hi": "पेड़ लगाने के साथ ऐसे उपाय भी होने चाहिए जो शहरों को जल्दी ठंडा करें।", "isCorrect": true}]'::jsonb, explanation = 'The passage grants that trees are ''the obvious remedy'' but shows that they work slowly, and ends by saying that a plan relying on trees alone will not help the next summer; quick measures such as cool roofs must sit alongside them. Saying that planting trees does little contradicts the passage, which calls trees the obvious remedy. Blaming tin roofs makes one cause the main one: the passage names both missing green cover and tin roofs. Counting surviving trees is a detail the passage mentions in passing, not its central point.', explanation_hi = 'परिच्छेद मानता है कि पेड़ ''स्पष्ट उपाय'' हैं, पर दिखाता है कि वे धीरे काम करते हैं, और अंत में कहता है कि केवल पेड़ों पर टिकी योजना अगली गर्मी में सहायता नहीं करेगी; ठंडी छतों जैसे जल्दी असर वाले उपाय उनके साथ चलने चाहिए। यह कहना कि पेड़ लगाने से बहुत कम लाभ होता है, परिच्छेद का खंडन करता है, जो पेड़ों को स्पष्ट उपाय कहता है। टिन की छतों को मुख्य कारण बताना एक कारण को मुख्य बना देता है: परिच्छेद हरियाली की कमी और टिन की छतें दोनों बताता है। बचे हुए पेड़ गिनने की बात एक ब्योरा है जिसका उल्लेख परिच्छेद चलते-चलते करता है, उसका केंद्रीय विचार नहीं।' where concept_group_id = 'csat-l2-t01-rc-p01-crux' and status = 'draft' returning concept_group_id;
update public.questions set body = 'Read the following passage and answer the item that follows. Your answer should be based solely on the passage.

Passage
Public trust in science is often discussed as though it were a fixed stock that experts either keep or squander. It behaves more like the trust people place in a doctor. People trust a doctor who explains what she knows and what she does not, who changes her advice when the evidence changes, and who does not pretend that a hard trade-off is a purely technical question. Scientists who, in a crisis, present every recommendation as certain may win obedience in the short run, but each later revision then looks like a broken promise. Admitting uncertainty feels risky to an expert facing an anxious public; in the long run, hiding it is riskier.

Which one of the following statements best reflects the crux of the passage?', body_hi = 'निम्नलिखित परिच्छेद को पढ़िए और उसके बाद दिए गए प्रश्नांश का उत्तर दीजिए। आपका उत्तर केवल परिच्छेद पर आधारित होना चाहिए।

परिच्छेद
विज्ञान में जनता के भरोसे की चर्चा प्रायः ऐसे की जाती है मानो वह कोई निश्चित भंडार हो जिसे विशेषज्ञ या तो बचाए रखते हैं या गँवा देते हैं। वह अधिकतर उस भरोसे की तरह व्यवहार करता है जो लोग किसी डॉक्टर पर करते हैं। लोग उस डॉक्टर पर भरोसा करते हैं जो बताती है कि वह क्या जानती है और क्या नहीं, जो प्रमाण बदलने पर अपनी सलाह बदलती है, और जो किसी कठिन संतुलन को पूरी तरह तकनीकी प्रश्न होने का दिखावा नहीं करती। जो वैज्ञानिक संकट के समय हर सिफ़ारिश को निश्चित बताकर पेश करते हैं, वे थोड़े समय के लिए आज्ञापालन पा सकते हैं, पर बाद में होने वाला हर संशोधन तब टूटे वादे जैसा लगता है। चिंतित जनता के सामने अनिश्चितता स्वीकार करना किसी विशेषज्ञ को जोखिम भरा लगता है; लंबे समय में उसे छिपाना अधिक जोखिम भरा है।

निम्नलिखित में से कौन-सा कथन परिच्छेद के सार को सबसे अच्छी तरह व्यक्त करता है?', question_data = '{"craft": "inference", "csat_set": "csat-l2-t01", "passage_group": "csat-l2-t01-p10", "csat_order": 69}'::jsonb, options = '[{"id": "a", "body": "Scientists should avoid giving any advice at all in a time of crisis.", "body_hi": "वैज्ञानिकों को संकट के समय कोई भी सलाह देने से बचना चाहिए।", "isCorrect": false}, {"id": "b", "body": "Experts keep public trust by being open about what they do not know.", "body_hi": "विशेषज्ञ यह खुलकर बताकर जनता का भरोसा बनाए रखते हैं कि वे क्या नहीं जानते।", "isCorrect": true}, {"id": "c", "body": "People trust their doctors far more than they trust scientists.", "body_hi": "लोग वैज्ञानिकों की तुलना में अपने डॉक्टरों पर कहीं अधिक भरोसा करते हैं।", "isCorrect": false}, {"id": "d", "body": "Once lost, public trust in science can never be won back again.", "body_hi": "एक बार खोया हुआ विज्ञान पर जनता का भरोसा फिर कभी नहीं लौटता।", "isCorrect": false}]'::jsonb, explanation = 'The passage argues that trust is kept by candour -- saying what is not known and revising openly -- and that projecting certainty backfires when advice changes. Avoiding advice in a crisis is not suggested; the comparison with doctors is an analogy, not a ranking of whom people trust more; and the passage rejects the view of trust as a fixed stock that, once lost, can never be won back.', explanation_hi = 'परिच्छेद का तर्क है कि भरोसा स्पष्टता से बना रहता है -- यह बताना कि क्या ज्ञात नहीं और खुलकर संशोधन करना -- और यह कि सलाह बदलने पर निश्चितता का दिखावा उलटा पड़ता है। संकट में सलाह न देने का सुझाव नहीं दिया गया; डॉक्टरों से तुलना एक उपमा है, यह क्रम नहीं कि लोग किस पर अधिक भरोसा करते हैं; और परिच्छेद भरोसे को ऐसा निश्चित भंडार मानने वाले दृष्टिकोण को नकारता है जो एक बार खो जाने पर कभी वापस नहीं मिलता।' where concept_group_id = 'csat-l2-t01-rc-p10-crux' and status = 'draft' returning concept_group_id;
