update public.questions set source_citation='NCERT Biology Class XII, ch. ''Organisms and Populations'' (responses to abiotic factors).' where exam_category='upsc' and subject='Environment & Ecology' and concept_group_id='env-aestivation-hibernation' and status='draft';
update public.questions set source_citation='NCERT Biology Class XII, ch. ''Organisms and Populations''.' where exam_category='upsc' and subject='Environment & Ecology' and concept_group_id='env-echolocation' and status='draft';
update public.questions set source_citation='NCERT Biology Class XII, ch. ''Organisms and Populations'' (population interactions: brood parasitism).' where exam_category='upsc' and subject='Environment & Ecology' and concept_group_id='env-koel-brood-parasite' and status='draft';
update public.questions set source_citation='NCERT Biology Class XII, ch. ''Organisms and Populations'' (adaptations to desert conditions).' where exam_category='upsc' and subject='Environment & Ecology' and concept_group_id='env-camel-hump-fat' and status='draft';
update public.questions set source_citation='NCERT Biology Class XII, ch. ''Organisms and Populations'' (Allen''s rule).' where exam_category='upsc' and subject='Environment & Ecology' and concept_group_id='env-arctic-fox-allens-rule' and status='draft';
update public.questions set source_citation='Botanical Survey of India, Nepenthes khasiana; NCERT Science Class VII (pre-2024 edition), ch. ''Nutrition in Plants''.' where exam_category='upsc' and subject='Environment & Ecology' and concept_group_id='env-insectivorous-plants' and status='draft';
update public.questions set source_citation='NCERT Science Class VII (pre-2024 edition), ch. ''Nutrition in Plants''; NCERT Biology Class XI, ch. ''Morphology of Flowering Plants''.' where exam_category='upsc' and subject='Environment & Ecology' and concept_group_id='env-epiphyte-vs-parasite' and status='draft';
update public.questions set source_citation='NCERT Biology Class XII, ch. ''Organisms and Populations'' (adaptations of plants to deserts).' where exam_category='upsc' and subject='Environment & Ecology' and concept_group_id='env-xerophyte-adaptations' and status='draft';
update public.questions set source_citation='NCERT Biology Class XII, ch. ''Ecosystem'' (ecological succession).' where exam_category='upsc' and subject='Environment & Ecology' and concept_group_id='env-lichen-pioneer' and status='draft';
